### ISSUE TITLE
"Quest Completed - New Quest" corrupting quests and randomly completing them

### ISSUE THREAD

**Issue by mcjacob** [NillerMedDild/Enigmatica2Expert#377] opened 2018-11-12 05:35 UTC
## Thank you for helping us improve. #####

_Please follow the issue template, and do not delete any part of it._
_Failure to comply will result in the issue being closed._

**Issue Description**

So I opened my first world on Enigmatica 2 - Expert, and I was instantly barraged by messages of "Quest Completed - New Quest" with a nether star icon (the default) underneath. Upon looking at the quest book, it seems as if the content of quests is being deleted, causing these quests to automatically complete.

**Modpack version (Do not use "latest")**

1.42a

**Logs**

N/A - not a crash, just messed up in game

**Screenshots**

**Additional context**

I literally just opened a new world for the first time

**Comment by NillerMedDild** [comment] 2018-11-12 07:07
Duplicate of #133 - There's a backups folder in the betterquesting folder of your world, you can load one of those up :)

**Closed by NillerMedDild** 2018-11-12 07:07 UTC
