### ISSUE TITLE
Thaumic Tinkerer is non functioning

### ISSUE THREAD

**Issue by SeanMFranklin** [NillerMedDild/Enigmatica2Expert#1715] opened 2020-05-22 11:17 UTC
**Modpack version**
1.8

**Issue**
None of the thaumic tinkerer research completes, and there is no research or reciper for the attractors, corporeal and kinetic.

These items do seem to function though, just aren't obtainable. Maybe consider adding recipes for them, and updating thaumic tinkerer.

**Comment by NillerMedDild** [comment] 2020-05-22 17:01
duplicate of #1026 
We're waiting for the new updates to stabilize.

**Closed by NillerMedDild** 2020-05-22 17:01 UTC
