### ISSUE TITLE
Advanced rocketry rockets bugged

### ISSUE THREAD

**Issue by HerrHebel** [NillerMedDild/Enigmatica2Expert#1472] opened 2020-01-01 22:45 UTC
**Modpack version**
1.74

**Issue**
When finally reached the point where I could tinker with advanced rocketry and I was really disappointed that it doesn't work. 
Rocket always lands on some insane y levels (tried it on space station, moon, mercury and earth - always the same thing, sometimes y=100 sometimes 800, no rule here). Apon clicking disassembly the rocket disappears instead of becoming a cluster of normal blocks. Due to that issue refueling is not possible and further space exploration (and pack progression) is really difficult (or rather annoying)

I tried it also with a rocket built on space station (so the launching pad was present) then warping somewhere else, landing on new planet (landed on high Y level) and coming back (also landed on high Y level despite having a launchpad on the station)
https://imgur.com/a/ixqLzDa

**Comment by HerrHebel** [comment] 2020-01-01 23:16
Just discovered that when auto descending everything is ok, seems like pressing space to descent causes problems

**Comment by NillerMedDild** [comment] 2020-01-02 19:15
Thank you for the report, I will do my best to resolve the issue.

In regards to the invisible rocket issue, have you checked if relogging makes it re-appear?
Does it happen in single player, LAN or server?

**Comment by HerrHebel** [comment] 2020-01-04 16:06
Once it appearded after relogging, but apart from that Ive lost like 3 rockets. Finally managed to get all the extraterrestrial resources, but it was a hassle. Fortunately autodescend worked flawlessly.

And this happened on single player, with no changes to the pack apart from adding veinminer, which I prefer over ore excavation for some reason ;)

**Comment by NillerMedDild** [comment] 2020-01-04 16:36
You weren't wearing a jetpack during the descent right?

**Comment by HerrHebel** [comment] 2020-01-04 19:39
Nope, had flux-infused armor with airtight seal enchant and angel ring as a bouble

**Comment by NillerMedDild** [comment] 2020-01-04 20:13
Could you have activated the Angel Ring's flight by pressing space? 
Would you mind trying to replicate the bug without the Angel Ring?

**Comment by Atadele** [comment] 2020-01-08 09:27
**HerrHebel** were you having a problem only when you pressed space to descend? It is like the altitude goes down and up very fast? Having a problem when I press space the altitude goes crazy and the rocket won't land. Just wanted to know if this was similar.

**Comment by HerrHebel** [comment] 2020-02-04 11:17
Sorry m8s, didnt have much time in Januray to play. I've tried it now with empty inventory, just armor and teleport thingy from RFtools, angel ring left in overworld. Still the same issue when forcing landing but it seems to be better now, the rocket doesnt land 400m above the ground but rather ~100m.

And yes, when you force landing the altitude meter goes crazy AF, whereas when you let the timer count down it goes smoothly  @Atadele

**Comment by Splutty** [comment] 2020-05-22 12:15
This is still an issue in E2E 1.80. I'm right now looking at an invisible rocket and smashing my face into it. When I look at the rocket assembler it gives me a "Missing Guidance Computer". Scanning causes the scan frame to rapidly appear, but do nothing.

**Comment by NillerMedDild** [comment] 2020-05-22 17:03
We know, that's why the issue is open :)

**Comment by Splutty** [comment] 2020-05-22 23:26
Was just making sure and adding some more info :D

**Comment by NillerMedDild** [comment] 2021-03-06 20:56
I do not believe I can fix this, and the majority of modders no longer support 1.12, so I'll close this issue.

Nethertheless, thank you for reporting :)

**Closed by NillerMedDild** 2021-03-06 20:56 UTC
Labels: Mod Issue, Status: Reported, Status: Unresolved

**Comment by Splutty** [comment] 2021-03-06 23:47
You're welcome, I don't even know if it's your mod or a combination with one of the many others in Enigmatica 2 :(
