### ISSUE TITLE
Strange Fullscreen with certain characters

### ISSUE THREAD

**Issue by Problembeloeser** [NillerMedDild/Enigmatica2Expert#1639] opened 2020-04-12 15:26 UTC
**Modpack version**
1.78

**Issue**
When trying to type certain characters like '*' or '?', the game goes in fullscreen mode instead. This behaviour is tested on vanilla and doesn't reproduce there. Note, that I am using Arch Linux with XFCE4 as GUI.
It seems like most keys on the keyboard which produce a visible character except letters and numbers do activate fullscreen mode. Of course, the hotkeys for fullscreen is not set.

**Logs**
No log output is produced with this behaviour

**Comment by KleinGrrmpf** [comment] 2020-04-12 16:51
I have a similar problem: 
When I have an open GUI (i.e. inventory, crafting table...) and press one of the other buttons on my mouse (not right/left/middle mouse button, but thumb button etc.), the game goes in fullscreen mode. I don't think that this is a problem that is caused by the modpack specifically, but by sth a mod adds.

**Comment by MorganSimic** [comment] 2020-04-12 18:02
It's something weird that that the Borderless Fullscreen mod does. You can disable it's keybinds in the mod options wich fixes the weird key behaviour.

**Comment by Problembeloeser** [comment] 2020-04-12 18:07
@MorganSimic:
But Borderless Fullscreen is not included in this modpack, right? And I checked: the keys that cause the toggle are not only multiple ones, they not bound in the controls tab.

**Comment by NillerMedDild** [comment] 2020-04-12 18:26
It's a rare issue with a few operating systems, not much we can do about it I'm afraid :(

**Comment by viveleroi** [comment] 2020-04-12 19:55
This happens to me when I use my keyboard media controls (Windows 10, Corsair RGB mechanical keyboard). Super annoying when trying to pause/play my music. I'd prefer to not remove mods, manual changes get blasted if I update and forget, but I understand this may be a mod bug instead.

**Comment by MorganSimic** [comment] 2020-04-12 20:42
Also happens with multimedia keys on windows 7. When i use the buttons on my headset it also happens. Also with the `><|` key on a german QWERTZ keyboard. And the issue is only resolved by disabling the mod in the mod configs in game. Nothing else i tried did resolve this issue.

**Comment by KleinGrrmpf** [comment] 2020-04-12 21:23
> 
> 
> Also happens with multimedia keys on windows 7. When i use the buttons on my headset it also happens. Also with the `><|` key on a german QWERTZ keyboard. And the issue is only resolved by disabling the mod in the mod configs in game. Nothing else i tried did resolve this issue.

Yes, that key does it too when I accidentally press it.



> 
> 
> This happens to me when I use my keyboard media controls (Windows 10, Corsair RGB mechanical keyboard). Super annoying when trying to pause/play my music. I'd prefer to not remove mods, manual changes get blasted if I update and forget, but I understand this may be a mod bug instead.

The key on my mouse that does this is also the play/pause button on the mouse. 

So I guess it is a common thing that the pause button for music does somehow cause this issue

**Comment by NillerMedDild** [comment] 2020-04-13 06:26
Reported here: https://github.com/hancin/Fullscreen-Windowed-Minecraft/issues/31
I will remove the mod for the time being, I didn't think this issue was so common, sorry folks.

**Comment by NillerMedDild** [comment] 2020-04-13 19:00
While fiddling around with it I've had tons of issues, I'm removing it.

**Closed** 2020-04-13 20:22 UTC
Labels: Mod Issue, Status: Reported
