### ISSUE TITLE
Thermal Expansion Visual glitch

### ISSUE THREAD

**Issue by Pabsb** [NillerMedDild/Enigmatica2Expert#1269] opened 2019-07-08 20:04 UTC
**Modpack version**
Enigmatica 2 Expert 1.64d

**Can the issue be reproduced?**
Yes

**Logs**
N/A

**Issue**
When 2 portable tanks from Thermal expansion interact with each other they get a visual glitch showing the same level of liquid as the other. The visual glitch happens only when you use a tank to input or output fluid of another tank or when stacking them due to their nature of outputting liquids they have from the bottom of the tank.

**Comment by NillerMedDild** [comment] 2019-07-08 20:10
Thank you for the report. Can you please check if this issue also exists in 1.65d?

**Comment by Frikkle** [comment] 2019-07-09 08:53
I can confirm this happened on 1.64d and before. Not sure if it is still present. I also haven't been able to reproduce this in a consistent way.

The Waila fluid level display and the rest of the behaviour are correct. So this would purely be a visual thing.

**Comment by NillerMedDild** [comment] 2019-07-09 15:37
As I mentioned in the discord, is this issue worth pursuing? :)

**Comment by Frikkle** [comment] 2019-07-10 17:34
I don't think so. I wanted to create some steps to reproduce and then report it to them. Then mark it as low prio and close it here. Since it's not a functional bug I wouldn't keep it marked as such

**Closed** 2019-09-08 19:06 UTC
Labels: Priority: Low, Status: Unresolved, Type: Bug
