### ISSUE TITLE
Tinkers' Construct slimes do not spawn

### ISSUE THREAD

**Issue by Ieldra2** [NillerMedDild/Enigmatica2Expert#1407] opened 2019-11-04 07:14 UTC
Pack version 1.70c

Slime spawns on slime islands - whether in the overworld sky or on the Nether lava ocean - simply do not happen. It is remotely possible that I've just been unlucky, but slime spawns were very common in past versions of the pack, now exploration of about 20 slime islands yielded not a single slime spawned.

**Comment by NillerMedDild** [comment] 2019-11-04 07:52
Thank you for the report, I will investigate the issue.
This could be caused by updating TiC, but I can't remember if I did that atm ^^'

**Comment by maiky129** [comment] 2019-11-13 06:01
I am playing on 1.72 and my slime islands are not spawning slimes either. My slime island actually had 2 normal trees in addition to the slime trees, and there were 4 cows up there somehow...

**Comment by NillerMedDild** [comment] 2019-11-13 08:22
Silly question, but you're not in peaceful mode right?

**Comment by maiky129** [comment] 2019-11-13 08:50
No, I was in Hard mode

**Comment by bk-one** [comment] 2019-11-19 13:46
+1, can confirm - all islands empty

**Comment by NillerMedDild** [comment] 2019-11-19 18:20
But not old worlds?

**Comment by pjc21** [comment] 2019-11-20 09:32
If this helps, I checked in save game started in 1.69 now updated to 1.72 and found if I fly around and find a new undiscovered slime islands and fly straight to it and land on it, either no slimes have spawned or sometimes there are other entities up there (eg: deer, cows found so far) -
however if I find a new island and stop around 20-30 blocks away and wait for around 30ish seconds slimes will spawn.

**Comment by bk-one** [comment] 2019-11-20 09:55
Yes, can confirm that new chunks will spawn slime - the ones near my base remain empty though, even after minutes of waiting around. But I guess that's good enough? At least good enough to build a mob farm as suggested in #1424. So I think this can be closed.

**Closed** 2019-11-20 10:01 UTC
Labels: Type: Bug
