### ISSUE TITLE
Recipe Issue Adv. Rocketry Precision Assembler Liquid IO Circuit requires wrong fluid storage component

### ISSUE THREAD

**Issue by Hachuurui** [NillerMedDild/Enigmatica2Expert#356] opened 2018-10-29 03:17 UTC
## Thank you for helping us improve. #####

_Please follow the issue template, and do not delete any part of it._
_Failure to comply will result in the issue being closed._

**Issue Description**
Recipe for liquid IO Circuit in Precision Assembler Requires Extra Cells 2 1k fluid cell instead of the new Applied Energistics 1k fluid cell. EC2 Fluid cell is not craftable making this recipe not craftable.

**Modpack version (Do not use "latest")**

1.41

**Logs**

If applicable, please upload your crash report, or latest.log to [hastebin](https://hastebin.com/).

**Screenshots**

![2018-10-28_23 16 25](https://user-images.githubusercontent.com/2464584/47627642-94a69800-db07-11e8-8950-0d42ec1d0aa0.png)

**Additional context**

**Comment by NillerMedDild** [comment] 2018-10-29 06:11
Duplicate of #280

**Closed by NillerMedDild** 2018-10-29 06:11 UTC
