### ISSUE TITLE
Can't Craft Quantum Entangloporter

### ISSUE THREAD

**Issue by MrPryor** [NillerMedDild/Enigmatica2Expert#629] opened 2019-01-16 08:39 UTC
## Thank you for helping us improve. #####

_Please follow the issue template, and do not delete any part of it._
_Failure to comply will result in the issue being closed._

**Issue Description**
Can't Craft Quantum Entangloporter from Mekanism.

**Modpack version (Do not use "latest")**
Enigmatica 2: Expert v1.51
Mekanism-1.12.2-9.4.13.349

**Screenshots**
https://i.imgur.com/OcNwUHB.png

**Comment by Rseding91** [comment] 2019-01-16 10:14
Same issue with anything that takes forestry circuits through custom recipes. The addition of the ".withTag({})" on each of the circuits in the recipes is causing them to fail to be craftable. Deleting that tag fixes it locally although I don't know why it was added.

I suspect it's meant to be "with no tags" so if someone crafts tubes onto circuits it doesn't use that circuit - but it doesn't seem to be working.

**Comment by MrPryor** [comment] 2019-01-16 11:52
Any known easy fix?

**Comment by Rseding91** [comment] 2019-01-16 12:04
You can either edit the scripts yourself to delete the .withTag({}) entries or if you're in single player, get the items, delete them, and spawn in the item.

**Comment by NillerMedDild** [comment] 2019-01-16 13:55
`.withTag({})` Means it'll accept any NBT. The issue is that the Quantum Entangloporter only accepts Circuits without NBT data, since their NBT data was only added recently.

**Comment by NillerMedDild** [comment] 2019-01-16 13:55
Duplicate of #623 
Please check if your issue already exists in the future.

**Closed by NillerMedDild** 2019-01-16 13:55 UTC
Labels: duplicate
