### ISSUE TITLE
Adv Generators don't consume Gasses.

### ISSUE THREAD

**Issue by Zarklord** [NillerMedDild/Enigmatica2Expert#1517] opened 2020-02-06 15:53 UTC
**Modpack version**
1.76a

**Issue**
using gas input for ethylene in Adv Generators while needed, never actually consumes any ethylene in producing power, so for instance, using a Rotatry Condensentrator turning Liquid Ethylene in Ethylene,(at first, I tried using gas input, but that didn't work which is why I ended up testing this), and extracting it with a EIO ender gas conduit, results in ethylene getting put in the buffer, but never actually get consumed(after the buffer gets filled up that is), resulting in literally free power, costing nothing and(when using top tier materials) producing 80000 rf/t.

**Comment by NillerMedDild** [comment] 2020-02-06 17:32
Thank you for the report, I will investigate the issue.

**Comment by MorganSimic** [comment] 2020-02-07 21:37
I have heard indeed reports of Advanced Generators randomly bugging out and not using any fuel. Not specifically Ethylene but any fuel for the gas turbine controller. Haven't tested it for myself but something indeed seems to be off with those. But probably not really consistent, at least that's the word around the Discord.

**Comment by Zarklord** [comment] 2020-02-08 00:44
It consumed fuel right before I swapped to gas input, I think either EIO's gas conduits are the issue, or the gas input for adv generators is the issue...

**Comment by sarcastic6** [comment] 2020-02-11 13:29
I'm seeing the same thing.  It also happens with Mek pressurized tubes -- and even if I hook a PRC directly up to the gas input of an advanced generator.  Everything works fine while the generator fills its buffer (and if you use the "clear internal buffers" button in the generator it'll start consuming ethylene again) -- but as soon as its internal tank fills up it stops consuming fuel.

Interestingly, if you disconnect the gas conduit/tube (or break the thing directly connected), the advanced generator starts consuming fuel from its buffer again.

**Comment by NillerMedDild** [comment] 2020-02-19 20:10
I reproduced the bug and reported it here: https://github.com/mekanism/Mekanism/issues/5887

**Comment by NillerMedDild** [comment] 2020-02-19 21:01
https://github.com/bdew/generators/issues/195

**Comment by hinchy34** [comment] 2020-12-05 17:44
So I have just discovered this glitch, I put 1000 mB of ethylene (gas) into a basic gas tank from Mekanism with the gauge dropper and connected it directly to the advanced generators gas input... It only used 512 mB, leaving 488 mB in the Mekanism tank.

My advanced generator is making 80k rf/t. It's not clear to me if it is a Mekanism or Adv Generator bug, but it's pretty game breaking and I'm surprised it hasn't been disabled considering it's now December 2020.

**Comment by NillerMedDild** [comment] 2021-03-06 20:57
I do not believe I can fix this, and the majority of modders no longer support 1.12, so I'll close this issue.

Nethertheless, thank you for reporting :)

**Closed by NillerMedDild** 2021-03-06 20:57 UTC
Labels: Mod Issue, Status: Reported
