### ISSUE TITLE
Mekanism Cardboard box stuck in AE2 Storage cell

### ISSUE THREAD

**Issue by Terminuz** [NillerMedDild/Enigmatica2Expert#1337] opened 2019-09-05 13:13 UTC
**Modpack version**
1.64d

**Can the issue be reproduced?**
unknown

**Logs**

**Issue**
I used cardboard boxes from Mekanism on some spawners (Blaze from nether, zombie from vanilla and hobgoblin from Twilight Forest) dumped them into my ME system via an import port connected to an ender chest. After that I could not remove the boxes from the storage cell. neither through the regular terminal, wireless terminal or in an ME chest. The only way to remove it was using an IO Port to a chest in an isolated ME system. Empty boxes are fine. 

"Fand'me godt arbejde med den her pakke!" :-)

**Comment by NillerMedDild** [comment] 2019-09-05 15:17
Duplicate of #950 
Tak! :)

**Closed by NillerMedDild** 2019-09-05 15:17 UTC
