### ISSUE TITLE
White Screen When Looking at a Players Equipped with Azure Helmet

### ISSUE THREAD

**Issue by scorpio5** [NillerMedDild/Enigmatica2Expert#1244] opened 2019-06-14 01:52 UTC
**Modpack version**
1.64d

**Can the issue be reproduced?**
Yes

**Logs**
N/A

**Issue**
I am playing with a friend using LAN.  When he wears a Vision Helmet (by Cyclic) and I look at him, my screen turns white.  It is simply a white screen without UI elements or other graphics.  I am still able to move and hit objects.  If I hit him while white screened, the screen becomes normal for half a second and returns to white.  His player frame is outlined in white and can be seen through walls, similar to the Glow effect.

Even if the Vision Helmet is worn and taken off, without using the /effect clear command, the white screen continues to occur.

This is not an issue if I don't look at him, but even seeing him in my periphery make the screen white.  We got around this by simply banning the use of the Vision Helmet

**Comment by NillerMedDild** [comment] 2019-06-14 17:04
Thank you for the report, I will investigate the issue.

**Comment by Frikkle** [comment] 2019-06-15 10:15
I just tried to reproduce this issue on stock 1.64d and I could not reproduce it.

@scorpio5 are you running stock E2E? Or do you have any shaders going on?

Might be worth noting that I tested this with a Nvidea card; AMD might be a possible cause of the issue.

**Comment by scorpio5** [comment] 2019-06-15 15:04
I originally replaced BetterFPS with Optifine and used Sphax resource pack, but after the first couple white screens I reinstalled E2E to stock and the problem persisted.  I continued experimentation and it seems it only happens when I look at the host (in this case, my friend).  If the host looks at me when I wear the helmet, nothing happens.

In addition, it seems the white screen effect cannot be stopped by /effect clear.  It must be reset by death of the person who wears the helmet.

I am using GTX 1070 and Windows 10 if that helps.

**Comment by Frikkle** [comment] 2019-06-20 16:00
I've tried this some more and I cannot seem to reproduce it.

**Comment by NillerMedDild** [comment] 2019-06-20 16:39
This is the 4th time I've heard of the issue, so I guess it's just extremely hard to reproduce, maybe dependant on specific hardware.

**Comment by Frikkle** [comment] 2019-06-20 16:52
@scorpio5: does this issue occur only to you? Or to all of your friends as well?

**Comment by NillerMedDild** [comment] 2019-06-20 17:26
> If the host looks at me when I wear the helmet, nothing happens.

**Comment by Frikkle** [comment] 2019-06-20 18:24
Ah check, missed that. But that might make this just more likely to be something hardware/driver specific. I'd try updating my drivers as well as Java. Do a full reinstall of the pack on top of that and hope for the best.

**Comment by scorpio5** [comment] 2019-06-21 23:10
> @scorpio5: does this issue occur only to you? Or to all of your friends as well?

I recruited another friend for testing, and it seems the helmet effects other players and computers.  The only person not effected is the host.  My friend was blinded by white when the host wore the Azure helmet.   For some reason, this messed up his client and he had to do a full reinstall.

I, along with the host, updated nvidia drivers, updated Java, and reinstalled the pack but this problem has persisted.  The majority of the playing experience isn't hampered, because the Azure helmet seems to be the only item that causes this white screen.

Would a video of this issue be useful?

**Comment by Frikkle** [comment] 2019-06-22 05:46
It could be, yes.

And:
- could you stop the server, start it up again, both log in, cause the issue occur and then post the latest server log so that I can go through them. [To check compatibility issues and the present modlist]
- could you and him together go naked with empty inventories to the middle of nowhere on your server (a place with no player-built stuff, like 2k blocks away from civilisation) and try to reproduce it there? [To check for other mods/blocks interfering]
- try to reproduce it with a freshly crafted Vision Helmet? [To check if the specific helmet (possibly retrieved from a corrupt loot chest) is broken]
- in the issue title you mention "Azure Helmet" while in the body of the issue you mention "Vision Helmet". Could you let us know what's up with that?

**Comment by scorpio5** [comment] 2019-06-23 03:32
Sorry, I always confuse the names.  In both cases, I am talking about the Vision Helmet.  I will test the effect on a new world with you recommendations.  However, we use LAN, so I don't know if we'll be able to get server logs.

In addition, this issue has appeared with different items.  Other players on our LAN server have experienced whitescreen seconds after noticing the glowing effect on other players.  It seems the Vision helmet is not the root cause.

**Comment by scorpio5** [comment] 2019-06-23 03:38
Test 1) Got onto a new world.  No machinery.  Used creative mode to get crafting supplies.  Built Vision Helmet.  LAN host put on helmet.  When I was looking away, screen was normal.   When I turned to look at him, screen became white.

Also, in the above post, I mention that it appeared with different items.  We're not sure what item caused it, but it started when one of our players crafted a laser (we don't know the specific name of the item, he just  said that it's a laser).

We will try to record the problem tomorrow.

**Comment by Frikkle** [comment] 2019-06-23 06:21
Thanks for getting back us with the feedback; these sort of more detailed reports can help narrowing issues down. As to the LAN-part; I have tested this with client-server setups, not with a LAN world. I will try to replicate your steps tomorrow at work.

**Comment by Frikkle** [comment] 2019-06-25 07:41
I just tested with @stefancdr this at the office on a LAN setup.

Steps to reproduce:
1. Open local world to LAN (as player A).
2. Player B joins the game from local network (different machine).
3. Player A gives himself a Vision Helmet.
4. Player A gives equips the Vision Helmet.
5. Player B's screen goes instantly white.

Maybe step 5 happens already when player A gives himself the helmet; not sure. We did not do very extensive testing because every time you need to restart the client.

Symptoms for player B:
- Completely white screen.
- Player does walk and look around as expected (seen by player A).
- All menu options are non-responsive for player B.

This is caused by an NPE in rendering; Stefan will post this exception shortly. So we can report/fix/PR it. Should be a relatively easy fix.

**Comment by stefancdr** [comment] 2019-06-25 07:42
`
[09:34:01] [Client thread/ERROR]: Couldn't render entity
java.lang.NullPointerException: null
	at de.eydamos.backpack.model.LayerBackpack.doRenderLayer(LayerBackpack.java:36) ~[LayerBackpack.class:?]
	at de.eydamos.backpack.model.LayerBackpack.func_177141_a(LayerBackpack.java:14) ~[LayerBackpack.class:?]
	at net.minecraft.client.renderer.entity.RenderLivingBase.func_177093_a(RenderLivingBase.java:439) ~[caa.class:?]
	at net.minecraft.client.renderer.entity.RenderLivingBase.func_76986_a(RenderLivingBase.java:186) [caa.class:?]
	at net.minecraft.client.renderer.entity.RenderPlayer.func_76986_a(RenderPlayer.java:71) [cct.class:?]
	at net.minecraft.client.renderer.entity.RenderPlayer.func_76986_a(RenderPlayer.java:28) [cct.class:?]
	at net.minecraft.client.renderer.entity.RenderManager.func_188391_a(RenderManager.java:384) [bzf.class:?]
	at net.minecraft.client.renderer.entity.RenderManager.func_188388_a(RenderManager.java:368) [bzf.class:?]
	at net.minecraft.client.renderer.RenderGlobal.func_180446_a(RenderGlobal.java:628) [buy.class:?]
	at net.minecraft.client.renderer.EntityRenderer.func_175068_a(EntityRenderer.java:1347) [buq.class:?]
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1259) [buq.class:?]
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1062) [buq.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1119) [bib.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398) [bib.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:123) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_211]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_211]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_211]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_211]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
`

**Comment by stefancdr** [comment] 2019-06-25 07:55
Caused by https://bitbucket.org/eydamosminecraft/backpacks/src/MC1.12.x/src/main/java/de/eydamos/backpack/model/LayerBackpack.java on line 36. For some reason, `ItemStack backpack = Backpack.proxy.getClientBackpack(player);` returns null, this is not checked in the code.

**Comment by NillerMedDild** [comment] 2019-06-25 17:54
Great work you two!

**Closed** 2019-09-08 19:06 UTC
Labels: Status: In Progress, Status: Unresolved, Type: Mod Issue
