### ISSUE TITLE
Required Uncraftable Items

### ISSUE THREAD

**Issue by SuohKami** [NillerMedDild/Enigmatica2Expert#296] opened 2018-10-06 19:29 UTC
**Issue Description**
The Mekanism Basic Fluid Tank and Basic Gas Tank are unable to be crafted which prevents progression in multiple ways.
![basic fluid tank](https://user-images.githubusercontent.com/37942820/46575071-2d138780-c963-11e8-9f53-bbb3ee5f6c7e.png)

The screenshot included shows only 4 ways to obtain the Basic Fluid Tank, but those are just fluid filling and not true ways to craft it.

The Basic Gas Tank as no NEI GUI at all indicating there is absolutely no way to obtain or craft it.

**Modpack version (Do not use "latest")**
1.39

**Comment by SuohKami** [comment] 2018-10-06 19:32
Also now adding in: Basic Energy Cube, Basic Induction Provider and Basic Induction Cell have absolutely no way to obtain or craft

**Comment by NillerMedDild** [comment] 2018-10-06 19:49
Duplicate of #284 
Please look at closed issues before opening a new one. I have released a hotfix, it's awaiting approval.

**Closed by NillerMedDild** 2018-10-06 19:49 UTC
Labels: duplicate

**Comment by SuohKami** [comment] 2018-10-06 20:01
Sorry I only look at open issues, not closed ones, I didn't see a similar issue in open tickets.
