### ISSUE TITLE
Large amount of Recipe changes and missing after upgraded to 1.38

### ISSUE THREAD

**Issue by KingFishQiu** [NillerMedDild/Enigmatica2Expert#286] opened 2018-10-04 19:54 UTC
## Thank you for helping us improve. #####

_Please follow the issue template, and do not delete any part of it._
_Failure to comply will result in the issue being closed._

**Issue Description**
Dear NillerMedDild,

So, I found that there are extremely amount of recipe change/missing in the 1.38 version. I don't know if they are intended. Most of them are makanism. 

Including: 
**ME fluid storage from 4k to above
Mekanism: Basic Tank, basic gas tank, basic induction cell, basic energy cube (They are missing)**

Also, Diamond gear was changed from a mod to another.... Not a big deal
And stone gear recipe changed to a much easier one (not a big deal

**Modpack version (Do not use "latest")**
1.38A

**Logs**

If applicable, please upload your crash report, or latest.log to [hastebin](https://hastebin.com/).

**Screenshots**

**Additional context**

**Comment by NillerMedDild** [comment] 2018-10-04 19:59
Duplicate of #284

**Closed** 2018-10-04 20:00 UTC
Labels: duplicate
