### ISSUE TITLE
Server crashing on launch 1.59a

### ISSUE THREAD

**Issue by synewave** [NillerMedDild/Enigmatica2Expert#1027] opened 2019-03-26 21:44 UTC
**Modpack version**
1.59a Server Files

**Can the issue be reproduced?**
Yes

**Logs**
https://pastebin.com/vJZnfYNe

**Issue**
Server crashes while starting up after updating to 1.59a from 1.58, downgrading back to fresh 1.58 files launches the server fine.

Client has no issues launching when updated to 1.59a

**Comment by triasinformatica-gabe** [comment] 2019-03-26 22:01
Did you do the following as listed in the changelog?

> It's advised to run the command /bq_admin default load if you are updating from 1.58 or earlier.

(not sure if this is related; I just read it a few minutes ago while browsing)

**Comment by synewave** [comment] 2019-03-26 22:10
If I remember correctly that command is used in-game to refresh the Quest Book. Unless I'm able to do in the server console, I can't do the command because I can't get on the server in the first place.

**Comment by MaxNeedsSnacks** [comment] 2019-03-26 22:21
Assuming this is a duplicate of #1020. Same crash message and everything. Something‘s probably fucked up with FoamFix or another coremod... ugh

**Comment by MaxNeedsSnacks** [comment] 2019-03-26 22:24
Moving this to #1020.

**Closed by MaxNeedsSnacks** 2019-03-26 22:24 UTC

**Comment by NillerMedDild** [comment] 2019-03-26 22:27
The author of the first report was able to get back on his server with these steps:

**Comment by NillerMedDild** [comment] 2019-03-26 22:34
That reporter found a fix:
> SMP worked out of the box
> Server is where I developed the issue
> 
> Ok from what I did was like I normally do
> 
> 1)BACKUP BACKUP BACKUP
> 2) Delete config, mods, schematic, and script, directory
> 3) copy all files from the new zip to the directory
> 4) Run the serverstart.bat file
> 
>     1. Crash
> 
> 
> Then to fix what I did
> 
> create anew directory with just the new download in it and run the serverstart.bat and chnage eula
> it create a new world.. works..
> copy over my world to it and it also worked..
> 
> something in old directory keeping new download from working with the rest of the old files -world
> 
> hope that helps

**Comment by synewave** [comment] 2019-03-26 22:36
I will try that, thanks for the help

**Comment by MaxNeedsSnacks** [comment] 2019-03-26 22:36
Ohhhh, it might be library files or mixins!

**Comment by MaxNeedsSnacks** [comment] 2019-03-26 22:37
Yeah it’s probably an old mixin causing for a problem, then.

**Comment by synewave** [comment] 2019-03-26 22:44
Where do I find these mixin files? I can try this in addition to testing the transferring over the old world to a fresh install.

**Comment by MaxNeedsSnacks** [comment] 2019-03-26 22:45
It’s the .mixin.out directory ^^ also you COULD try to also delete the libraries folder since, if I remember correctly, the server start script we use reinstalls them if they’re not there right?

**Comment by synewave** [comment] 2019-03-26 22:48
Unless its hidden in some way, I actually don't have a folder called .mixin.out in my server files. I will try deleting the libraries folder though.

**Comment by MaxNeedsSnacks** [comment] 2019-03-26 22:53
Something else then... The „from scratch“ approach definitely works though (see the other issue again), but... what causes the error then? :/

**Comment by NillerMedDild** [comment] 2019-03-27 05:14
It didn't happen on my test server by the way, so it doesn't happen every time.
