### ISSUE TITLE
Stuttering/rubberbanding in server-controlled player movement

### ISSUE THREAD

**Issue by jngeist** [NillerMedDild/Enigmatica2Expert#1544] opened 2020-02-24 19:19 UTC
**Modpack version**
1.74, single-player.

**Issue**
In certain kinds of server-controlled player movement, I experience minor to severe rubberbanding.

- *[Advanced Rocketry rockets.](https://v.usetapes.com/5wUxDgihms)* I believe this is connected to [this issue](https://github.com/NillerMedDild/Enigmatica2Expert/issues/1472), as I experience them at the same time. In a descending rocket, my y-level jumps back and forth from what I think is my "real" y-level to a y-level about 3-500 blocks above that. You'll notice in the video that the rocket thinks it has "landed" way above the actual planet's surface. Sometimes, when I leave the rocket and head down to the ground, the rocket will fall out of the sky; other times, it's just lost. If it happens to get stuck below the max build height, I can disassemble it and break it down, but this happens only rarely.

    You'll also notice that my player location seems to be desynced with the rocket's location. I'm stuttering worse than the rocket is, I guess? Returning to my space station, I waited for auto-descend rather than pushing spacebar. I experienced less rubberbanding, and the rocket stopped at Y=368 without seeming to be aware that it had done so. It doesn't think it has landed, because it won't allow me to take off, but it is also no longer moving at all.

- *[Botania Luminizers.](https://v.usetapes.com/EwkVuh3w2V)* The rubberbanding isn't nearly as dramatic in this case, but if you watch the linked video, you'll see that it's still really jerky--low FPS notwithstanding.

I don't experience this with minecarts or viaducts, including long-range viaducts.

I realize my system performance is not the best, but I'm at 20 TPS across all dimensions and this is the only time I ever experience stuttering/rubberbanding of this kind.

**Logs**
[Log of recorded session.](https://paste.ee/p/KxcIr)

**Comment by NillerMedDild** [comment] 2020-02-24 19:36
First of all, excellent report, albeat a bit lengthy.

As you mention, the AR issue sounds a lot like #1472 - Identical in fact.

As for the Luminizers issue, I see on the Botania issue tracker that they have received bug reports about the Luminizer being janky, but the reports have remained unanswered. Because of this, I think it would be a waste of time to take it further to be honest, unless you think the issue is really annoying, in which case I will relay it.

**Comment by jngeist** [comment] 2020-02-24 19:48
I do find it annoying, but if it's already reported on the Botania side, I don't know that there's any need to bother yourself with it. I should've checked over there; I just assumed since it seemed connected to the Advanced Rocketry issue, that it was a pack interaction of some sort.

As to the Advanced Rocketry issue, I missed the comment about the altitude meter toward the end of the original thread, and I didn't see any mention of visual stuttering or rubberbanding. I knew I was having the issue mentioned in #1472, but I thought the movement glitches might be a separate issue. I also seem to experience the issue on auto-descent as well. Feel free to delete or mark as duplicate if it's connected.

**Comment by NillerMedDild** [comment] 2020-02-24 20:08
The AR issue is pretty broad, I've seen it do about 5 different glitchy behaviours :P Sometimes with a desync, sometimes no glitch, sometimes I actually land on Y=300.

I'll report the Luminizer issue if I can reproduce it :)

**Comment by NillerMedDild** [comment] 2020-02-24 20:18
I'm afraid I cannot reproduce it :/ So I'll close the issue as part duplicate and part cannot reproduce.

**Closed by NillerMedDild** 2020-02-24 20:18 UTC
