### ISSUE TITLE
Modular Machinery Power fluctuation / FluxNetworks

### ISSUE THREAD

**Issue by IC-SubiX** [NillerMedDild/Enigmatica2Expert#1065] opened 2019-04-05 18:08 UTC
**Modpack version**
Enigmatica 2: Expert 1.59a

**Can the issue be reproduced?**
unknown / (yes on same insatance in MultiMC)

**Logs**
-/-

**Issue**

All the Modular Machines (MM) have a strong power fluctuation if any Energy point (Flux Networks) is connected to the energy input. (even if there are EnderIO conduits between flux point and energy input). If transferlimit is set to any value, lets say 12.345rf/t, the energy level in the UI of the energy inport block jumps form 0 to that value (so 12.345) and back again. (i think its every gametick) If items are aviable for crafting it will start, but imidiatly stop and say "no Power".
I found one workaround with connecting a Ultimate energy Cell (Mekanism) to power it, but the transfer of rf is way to slow.

--I think it could also be a problem form FluxNetworks--

looks like:  https://github.com/NillerMedDild/Enigmatica2Expert/issues/973
i thougt the fix would do it :-|

And by the way your doing a great job! I love that Modpack!!!

Updated form 1.56 to 1.59a (expert), no futher Mods added!

Is ther anything i'm doing wrong?

greetings form Germany
IC_SubiX

**Comment by NillerMedDild** [comment] 2019-04-05 20:15
You need to give it at least 100.000 RF/t, are you doing that? 
Have you tried breaking and replacing the Energy Input Port? 
Does your Flux Network contain power, and is that amount higher than it's max?

**Comment by NillerMedDild** [comment] 2019-04-05 20:15
And thank you :D

**Comment by IC-SubiX** [comment] 2019-04-07 13:26
> 
> 
> You need to give it at least 100.000 RF/t, are you doing that?
> Have you tried breaking and replacing the Energy Input Port?
> Does your Flux Network contain power, and is that amount higher than it's max?

Yea, i use NC Fusion (2.8M rf/t) and 20 ultimate Inductions cells  (Mekanism) so ther is plenty power aviable (no limit in transferpoint).
Yes, i rebuild the whole MM, even in a different chunk. 

No ther is no power stored in the FN.

**Comment by NillerMedDild** [comment] 2019-04-07 13:47
Could you try with a new Flux Network please?

**Comment by IC-SubiX** [comment] 2019-04-07 14:28
Ok i will try that, but I will not play again until Thursday.

**Comment by jmarler** [comment] 2019-04-12 04:46
I am seeing a similar issue with the modular machines as well in 1.60. I see the same peculiar behavior with Flux networks. Also, if I take the flux network out of the equation, I still see problems. For example, I can put an advanced energy cube from Mekanika with 3.2MRF fully charged directly next to the energy input. When I attempt to craft a single recipe of osgloglass, I can watch the energy cube slowly drain of all FE. The interface on the modular machine says "Not enough energy" and the craft never completes. The energy cube will completely drain all 3.2MRF, but the craft never completes. I created a new flux network, and it behaves differently. The interface on the module machine still says "Not enough energy" but the craft will eventually complete. I created a new Flux network as you suggested, but this also exhibits odd behavior. When looking at the flux point, while the "Not enough energy" message is displayed, 0FE are being transferred, and the machine's energy input is full. This continues for several seconds, then a burst of FE is transferred at 100 KFE/T, and the craft completes, about every 4 seconds. I see the same behavior with Mirion. With the new network, the crafts are slow, but they do eventually complete. With the old network though, it just flickers if I use a point, and if I use an advanced energy cube, the cube just drains and the craft never completes. Something is behaving very oddly.

**Comment by NillerMedDild** [comment] 2019-04-12 05:45
The Advanced Energy Cube can't transfer energy fast enough, you need to supply the MM with at least 100KRF/t. 
The Flux Network behaviour you're seeing is most likely caused by the MM not drawing power until the end of the craft, I think.

**Comment by IC-SubiX** [comment] 2019-04-12 16:57
So, finaly i invested time to gather informations.
1. I downloaded the E2E 1.60 and launched it with 6.5 GB Ram.
2. I copied the save folder and the options file and launched the game again
3. While joining the world i started OBS for video proof.
4. It is lagging way more than the same setup on 1.56 !?! (video is 5 fp min. !?!)
5. The Energy storage has plenty of juice and FN is outputing and insterting power.
6. My p2p tunel ME-core seems to have no power. It's getting power from the same TN (tranfer node) as the main ME-core. Added 2 Densed Energy Cells and got it to work.
7. Starded autocrafting to test the system. 
8. MM seems to work on a 50/50 chanse. 
9. Created a new network as told, but ther were no changes at all. (did not replace every singe TN, just the important ones)
10. also on crafting Osgoglas that happend:
"The interface on the module machine still says "Not enough energy" but the craft will eventually complete. When looking at the flux point, while the "Not enough energy" message is displayed, 0FE are being transferred, and the machine's energy input is full. This continues for several seconds, then a burst of FE is transferred at 100 KFE/T, and the craft completes, about every 4 seconds." -jmarler-
11: The MM thermionic fabricator seems to work fine now (not in 1.59a)!?!
12. Want to open Wireless-Crafting-Terminal and instantly crashed (i opend it cuple times before, and nothing happend). It's even more strange, because ther is no crash file in the MC folder!
13. restart and tryed to open WCT my hotkey is "<" on the german keybord its next to left shift. And that key got somehow bound to toggle Fullscreen but in the options its not bound to any key... and it crashed again (no crash file).

I found a new Bug:
Extra Utility and EnderIO item transport system seem to have big broblems to insert items into a drawer through a chunk border. It's not working at all! (the chunks are loaded via IC2 chunk loader, and also playerloaded)

I think i'm going to play on 1.56 as long my word is not behaving the right way.

Here are some more idears for features:
1. More endgame items e.g.(creative things from thaumcraft)
2. Usefull or fun (extra)-items ONLY aviable with UU matter. (e.g. IC2 p2p tunnel)
3. resetable consuming quests to get loot chests (e.g. ultimate ingot = loot chest)
4. Is it posible to add new fusion fuels? it would be amazing to be able to create more rf/t. I would use UU matter and neutron fluid at a very high tempreture (you need a good cooling setup) to generate insane amount of rf.
5. Secrets like a 128^3 special storage cell with something in it. So the players could build a special pylon chamber to unlock it. (like the 1.7.10 FTB materials energy 4 map) This system is so underrated and would be so cool to add again. (if you're interested i could help you)

**Comment by NillerMedDild** [comment] 2019-04-12 17:16
Don't pack feature requests into your bug report, and don't report new bugs in existing bug reports, please. 

So from all that information, I gather that the issue is actually fixed on 1.60? 
Based on `The MM thermionic fabricator seems to work fine now (not in 1.59a)!?!`

**Comment by IC-SubiX** [comment] 2019-04-12 19:54
> 
> 
> Don't pack feature requests into your bug report, and don't report new bugs in existing bug reports, please.
> 
Ok sorry!

> So from all that information, I gather that the issue is actually fixed on 1.60?
> Based on `The MM thermionic fabricator seems to work fine now (not in 1.59a)!?!`

I think so. Sometimes the FN is a bit funky (ME core), but i can work around it.

**Closed** 2019-04-12 20:10 UTC
