### ISSUE TITLE
Ender generator crashes game

### ISSUE THREAD

**Issue by kyle524** [NillerMedDild/Enigmatica2Expert#702] opened 2019-01-25 15:40 UTC
## Thank you for helping us improve. #####

_Please follow the issue template, and do not delete any part of it._
_Failure to comply will result in the issue being closed._

**Issue Description**
Shift clicking eyes of ender into the ender generator crashes the game, also adding more eyes of ender if there is already some in the generator causes them to disappear.

**Modpack version (Do not use "latest")**
1.53

**Logs**

If applicable, please upload your crash report, or latest.log to [gist](https://gist.github.com/).

**Screenshots**

**Additional context**

**Comment by NillerMedDild** [comment] 2019-01-25 16:59
Duplicate of #456

**Closed by NillerMedDild** 2019-01-25 16:59 UTC
Labels: duplicate
