### ISSUE TITLE
Immersive Engineering Crusher not crushing ores

### ISSUE THREAD

**Issue by CptTrilby** [NillerMedDild/Enigmatica2Expert#1881] opened 2021-01-17 05:15 UTC
**Modpack version**
1.82a

**Issue**
The Immersive engineering crusher multiblock will not crush ores, it will just get "stuck" and continue to crush endlessly without outputting anything. It crushes cobblestone fine.

EDIT:
found a similar problem in another modpack. https://github.com/FTBTeam/FTB-Continuum/issues/314

**Comment by NillerMedDild** [comment] 2021-01-17 10:08
duplicate of #1841

**Closed by NillerMedDild** 2021-01-17 10:08 UTC
