### ISSUE TITLE
Freeze when throwing Dragon's Breath at ender dragon

### ISSUE THREAD

**Issue by hamisht99** [NillerMedDild/Enigmatica2Expert#1352] opened 2019-09-15 06:41 UTC
**Modpack version**
1.6.8

**Can the issue be reproduced?**
Yes

**Logs**
[latest.log](https://github.com/NillerMedDild/Enigmatica2Expert/files/3613460/latest.log)

**Issue**
Throwing a bottle of dragons breath at the ender dragon causes the game to freeze and not recover.  Any world this occurs in can no longer be loaded without freezing.
The throwing can be accidental since dragons breath will automatically be moved to your hotbar once you run out of empty bottles.

**Comment by NillerMedDild** [comment] 2019-09-15 17:51
Ouch, sounds like a nasty issue. Would you mind updating Quark and AutoRegLib and see if that resolves the issue, before I investigate further? :)

**Comment by NillerMedDild** [comment] 2019-09-15 18:11
Oh btw, in the `forge.cfg` file in the configs folder, line 59: Change `B:removeErroringEntities=false` to `B:removeErroringEntities=true` - It will let your game load.

**Comment by hamisht99** [comment] 2019-09-16 03:08
Updating those mods and config file seems to have fixed it.

**Comment by NillerMedDild** [comment] 2019-09-16 04:40
Only updating the config would have fixed it on it's own, so it's hard to know if the issue was fixed in the mod.

**Comment by BlueKingMuch** [comment] 2019-09-19 12:21
yesterday i had the same issue when i tried to gather Dragon's Breath. it must be that i accidentally threw Dragon Breath Bottles, then the server crashed. And when I restarted the server, it would continue to crash when I log in. I could only fix it by editing my playerdata nbt and removing the dragon breath bottles from my inventory. Although the bottles itself don't seem to be a problem, because my teammate (which with i am playing on the server) gave me some dragon breath bottles which he gathered without crashing and this doesn't seem to be a problem.

**Comment by NillerMedDild** [comment] 2019-09-19 17:21
We know what the issue is, we do not know if it happens in newer Quark versions. Thanks for your input though :)

**Closed** 2019-10-15 20:12 UTC
Labels: Status: Completed, Status: Reported, Type: Mod Issue
