### ISSUE TITLE
IC2 causing Exception in AstralSorcery - fixed in IC2 2.8.106-ex112

### ISSUE THREAD

**Issue by TigerWalts** [NillerMedDild/Enigmatica2Expert#561] opened 2019-01-06 15:51 UTC
**Issue Description**

IC2 causing Exception in AstralSorcery - fixed in IC2 2.8.106-ex112

IC2 was using `EntityPlayer` class on server side when it should be using `EntityPlayerMP`. This results in AstralSorcery throwing an exception in versions `1.0.4` and later.

More info in additional content below

**Modpack version (Do not use "latest")**

`1.49`

**Logs**

See additional context

**Screenshots**

N/A

**Additional context**

- https://github.com/HellFirePvP/AstralSorcery/issues/963
- https://github.com/HellFirePvP/AstralSorcery/issues/951

**Comment by NillerMedDild** [comment] 2019-01-06 15:53
Duplicate of #526

**Closed by NillerMedDild** 2019-01-06 15:53 UTC
