### ISSUE TITLE
IC2 server crash in 1.43

### ISSUE THREAD

**Issue by DrDarkfire** [NillerMedDild/Enigmatica2Expert#405] opened 2018-11-25 16:52 UTC
## Thank you for helping us improve. #####

_Please follow the issue template, and do not delete any part of it._
_Failure to comply will result in the issue being closed._

**Issue Description**
The IC2 version appears to crash the pack server side in the 1.43 release.

**Modpack version (Do not use "latest")**
1.43

**Logs**
https://hastebin.com/coxojimodu.rb
If applicable, please upload your crash report, or latest.log to [hastebin](https://hastebin.com/).

**Screenshots**

**Additional context**

**Comment by NillerMedDild** [comment] 2018-11-25 19:35
Duplicate of #402

**Comment by NillerMedDild** [comment] 2018-11-25 20:07
This is not a duplicate, I apologize.

**Comment by NillerMedDild** [comment] 2018-11-25 20:07
What was happening on the server when it crashed?

**Comment by NillerMedDild** [comment] 2018-11-25 20:09
According to the log, the server doesn't have access to read from the config file `IC.ini`?

**Comment by DrDarkfire** [comment] 2018-11-25 22:31
is it a new file in 1.43 because of the IC2 update? because we downgraded to 1.42a and the server started up without a hitch.

**Comment by NillerMedDild** [comment] 2018-11-26 05:41
Nope, but I did update IC2 in the latest update, so I'm guessing it's doing something weird. Thanks for checking if a downgrade helped, that makes the troubleshooting a lot easier :)

**Comment by DrDarkfire** [comment] 2018-11-26 16:02
yes its on startup. I think its possible some permissions were changed in the update.

**Comment by NillerMedDild** [comment] 2018-11-26 16:55
On your end, that is?

**Closed** 2018-12-11 08:11 UTC
Labels: mod issue
