### ISSUE TITLE
Advanced Generators Infinite Fuel Glitch

### ISSUE THREAD

**Issue by pcd1193182** [NillerMedDild/Enigmatica2Expert#1672] opened 2020-04-25 20:42 UTC
**Modpack version**
1.80

**Issue**
If you hook the output of a PRC producing ethylene directly to a Gas Intake Valve from Advanced Generators, the Advanced Generators multiblock structure will convert the input into liquid ethylene and store it, but won't consume it. You can draw arbitrary amounts of power and the PRC will never activate, its output buffer always full. Worked around by inserting a Rotary Condensentrator and using a Fluid Intake Valve instead.

If this should be filed against the Advanced Generators mod specifically, lmk, I wasn't sure if this involved inter-mod interactions that the pack author would want to look at first.

**Logs**
N/A

**Comment by NillerMedDild** [comment] 2020-04-25 20:47
Duplicate of #1517

**Comment by NillerMedDild** [comment] 2020-04-25 20:48
Thanks for the report anyway.

**Comment by Frikkle** [comment] 2020-04-27 08:45
Shouldn't this one be closed since it's a duplicate?

**Comment by NillerMedDild** [comment] 2020-04-27 13:30
Yup, I just forgot :D

**Closed by NillerMedDild** 2020-04-27 13:30 UTC
Labels: Duplicate
