### ISSUE TITLE
Wireless Crafting Terminal: Negative Energy 

### ISSUE THREAD

**Issue by S1lentN1ght** [NillerMedDild/Enigmatica2Expert#1462] opened 2019-12-28 15:06 UTC
**Modpack version**
Version 1.72b

**Issue**
Main Issue: When putting the Wireless Crafting terminal into Mekanism Matrix it gives it a massive negative energy feed. 

Note: Haven't moved over to 1.74 or 1.73 as it crashes when loading.

![Issue](https://user-images.githubusercontent.com/59313874/71545488-8f3a1d00-2959-11ea-84d5-1c32498be617.png)

**Comment by NillerMedDild** [comment] 2019-12-28 18:40
Yikes. I wonder if this is fixed in 1.73+ though - Could you provide the crash report from one of your attempts at updating?

**Comment by S1lentN1ght** [comment] 2019-12-29 02:17
Oh weird, I got home, and tried launching it again and It works now. If I remember correctly earlier it was having a problem with the Forge version or something causing it to crash. But 1.74 works now. ~And yeah the Terminal wasn't fun, had to trash it a make a new one.

**Comment by S1lentN1ght** [comment] 2019-12-29 03:07
Never Mind, Reloaded the game again updating my save, and now its crashing again, but it won't get me view the Crash Reports.

**Comment by NillerMedDild** [comment] 2019-12-29 07:08
Please supply the latest.log then, it's in the logs folder. Otherwise, you have a crash reports folder, it's probably in there.

**Comment by S1lentN1ght** [comment] 2019-12-29 14:08
[2019-12-29-1.log.gz](https://github.com/NillerMedDild/Enigmatica2Expert/files/4008103/2019-12-29-1.log.gz)

**Comment by S1lentN1ght** [comment] 2019-12-29 14:08
Just tried launching the game again, this is the result.

**Comment by NillerMedDild** [comment] 2019-12-29 14:51
The file I need is literally called latest :)

**Comment by S1lentN1ght** [comment] 2019-12-29 14:54
[latest.log](https://github.com/NillerMedDild/Enigmatica2Expert/files/4008155/latest.log)

**Comment by S1lentN1ght** [comment] 2019-12-29 14:54
This one?

**Comment by NillerMedDild** [comment] 2019-12-29 15:56
Yep that's the one!

The issue is your Java is outdated, follow these steps to update:

* Make sure you have the latest 64-bit Java installed
    https://www.java.com/en/download/manual.jsp Windows Offline (64-bit) is the one you need
* Go to the Twitch Minecraft settings
* Add `-version:1.8+` to the Additional Arguments

**Comment by Discomanco** [comment] 2019-12-29 15:56
If it crashes on startup, it's likely due to your outdated Java.
```
You appear to be using outdated Java. This is often caused by Twitch defaulting to an older version than you have available. Follow these steps to update.

* Make sure you have the latest 64-bit Java installed
    https://www.java.com/en/download/manual.jsp Windows Offline (64-bit) is the one you need
* Go to the Twitch Minecraft settings
* Add -version:1.8+ to the Additional Arguments
```

**Comment by S1lentN1ght** [comment] 2019-12-29 16:22
Okay, so i removed my old java with the uninstaller, and got the new one
setup, and added the new argument command to the twitch settings, but now i
get a new error popping up.
This claims to crash the game afterwards as well but doesn't actually
create a log for it as it occurs right after clicking the start button.

**Comment by Discomanco** [comment] 2019-12-29 17:03
That means you didn't get the 64-bit Java

**Comment by S1lentN1ght** [comment] 2019-12-29 18:13
Ahh, okay, i had misleadingly  downloaded the 32-bit version, fixed it and restarted and it works now, Thankyou.

**Closed** 2019-12-30 04:02 UTC

**Comment by NillerMedDild** [comment] 2019-12-30 05:12
Soo.. the overflow doesn't happen anymore?

**Comment by S1lentN1ght** [comment] 2019-12-30 10:49
Oh, yeah for some reason it stopped. I don't know what triggers it. So I
don't know if its "resolved." But it has started working again. If the
issue arises again I'll bring it back up and try to find out what I did
that changed what happened.

**Comment by tawcarroll** [comment] 2020-03-05 13:38
Just happened to me using a Mekanism Matrix too (exact same issue). Version is 1.75. Perhaps because the induction matrix has a very high output rate something funny is happening with overflow?

Frustrating because I have no idea how to give it "positive" energy now. I might just have to craft a new one.
