### ISSUE TITLE
Crash when crafting with Mekanism tanks in Tinkers' Construct crafting table

### ISSUE THREAD

**Issue by Pokefan6031** [NillerMedDild/Enigmatica2Expert#976] opened 2019-03-10 20:56 UTC
**Modpack version**
1.58

**Can the issue be reproduced?**
Yes

**Logs**
Input pastebin link to crash-report or latest log, if applicable

**Issue**
Crafting with Mekanism Advanced Tank in a Tinkers' Construct crafting table crashes the game. After relogging, the crafting table fails to render, but can still be used. If the tank is still in the crafting grid, this basically creates an infinite crash loop. This can be avoided by simply breaking the crafting table. This seems to be an issue with rendering the tank in-world, because crafting the basic tank doesn't cause a crash. Using a vanilla crafting, without item rendering, doesn't cause a crash. Using any other Mekanism tank doesn't cause a crash, but does result in a rendering error making the crafting table invisible but usable.

Update: Did some testing, and it seems the tank itself doesn't seem to cause the crash. The crash occurs when you put any item in the crafting table when it's invisible. Vanilla crafting table still works as normal.

**Comment by MaxNeedsSnacks** [comment] 2019-03-10 21:22
Duplicate of #957, which is a duplicate of #946, which is, finally, a duplicate of #345

**Closed** 2019-03-11 01:52 UTC
Labels: invalid
