### ISSUE TITLE
Add Extra Bees

### ISSUE THREAD

**Issue by cbruster** [NillerMedDild/Enigmatica2Expert#1032] opened 2019-03-27 22:15 UTC
Adding Extra Bees or the entire Binnie's Mods pack would overhaul the Forestry mod adding much more content and enhance industry. 

https://minecraft.curseforge.com/projects/binnies-mods

**Comment by NillerMedDild** [comment] 2019-03-28 07:37
Duplicate of #707 & #486

**Closed by NillerMedDild** 2019-03-28 07:37 UTC
