### ISSUE TITLE
Missing Mekanism Recipes

### ISSUE THREAD

**Issue by MarcinSzuba** [NillerMedDild/Enigmatica2Expert#284] opened 2018-10-04 17:56 UTC
**Issue Description**
There are no recipies for Mekanism's Basic Induction Cell and Basic Energy Cube. I won't add any further details cause I don't even know what to add. It's probably some error in code ;)

**Modpack version (Do not use "latest")**
1.38a

**Comment by MarcinSzuba** [comment] 2018-10-04 18:01
Your bot automatically closed issue, but it followed the template.

**Comment by NillerMedDild** [comment] 2018-10-04 18:02
It did not, you deleted a bunch of lines.

**Comment by NillerMedDild** [comment] 2018-10-04 18:03
Silly bot, now it won't let me reopen it :P

**Comment by NillerMedDild** [comment] 2018-10-04 18:05
Have you tried relaunching the pack? :)

**Comment by MarcinSzuba** [comment] 2018-10-04 18:08
I've just restarted it. If this occures again I'll just download it again.

**Comment by NillerMedDild** [comment] 2018-10-04 18:09
So... You fixed it?

**Comment by MarcinSzuba** [comment] 2018-10-04 18:19
Not yet. redeploying it. It's server so it takes a little more time.

**Comment by MarcinSzuba** [comment] 2018-10-04 18:57
Ok I've redeployed it twice and still no change. 

I'm adding the log file. Maybe it'll help.
[latest.log](https://github.com/NillerMedDild/Enigmatica2Expert/files/2447725/latest.log)

**Comment by KingFishQiu** [comment] 2018-10-05 15:00
Just curious, is it a universal problem or occurs randomly. 

Having the same issue here. :( Currently not influencing my part of the game but...

**Comment by NillerMedDild** [comment] 2018-10-05 18:08
It's in both Expert packs, but not E2

**Comment by matthew-houser** [comment] 2018-10-05 19:32
Done :) check your paypal later... and with that. I wish you a good weekend. looking forward to the update.

**Comment by NillerMedDild** [comment] 2018-10-05 19:35
That's gonna make for one hell of a beer :P thank you, I appreciate it :)

**Comment by dsledz** [comment] 2018-10-05 19:44
Downgrading CraftTweaker to CraftTweaker2-1.12-4.1.9.jar seems to give the recipes back. No idea on the cause.

**Comment by NillerMedDild** [comment] 2018-10-05 20:00
Thank you very much dsledz, that saved me a lot of time!

**Comment by mtimyself** [comment] 2018-10-06 05:54
The Chemical Oxidizer (for Gaseous Brine -> [...] -> Titanium) is also impacted by this and it does have a custom recipe. Just felt like I should mention it so you guys can have a look if that issue is also fixed by the downgrade.

**Comment by NillerMedDild** [comment] 2018-10-06 13:46
https://github.com/CraftTweaker/CraftTweaker/issues/634

**Closed** 2018-10-06 19:10 UTC
Labels: mod issue
