### ISSUE TITLE
Immersive Engineering Assembler Not Working

### ISSUE THREAD

**Issue by Dory05** [NillerMedDild/Enigmatica2Expert#1246] opened 2019-06-17 22:25 UTC
**Modpack version**
Engimatica 2 (Can't Find)

**Can the issue be reproduced?**
Yes, has occurred in two separate worlds with five different setups.

**Issue**
While attempting to use the Assembler from immersive engineering, the item will not craft, even with normal redstone control.

**Comment by NillerMedDild** [comment] 2019-06-18 04:00
Probably duplicate of #786, I can't fix it I'm afraid.

**Closed by NillerMedDild** 2019-06-18 04:00 UTC
