### ISSUE TITLE
Cyclic food buffs lost upon death.

### ISSUE THREAD

**Issue by spdkils** [NillerMedDild/Enigmatica2Expert#876] opened 2019-02-21 01:35 UTC
**Modpack version**
1.54

**Can the issue be reproduced?**
Yes

**Issue**
Eat a food_step or inventory_food.

Put stuff in your inventory.

Die....

Lose all high step, and lose access to that inventory till you eat the items again.

I think it may be a mod conflict of some sort.  Because I used cyclic in another mod pack, and I scoured the config, cannot find where you lose the buffs on death.

If this is a feature request, feel free to delete the template.

**Comment by NillerMedDild** [comment] 2019-02-21 07:48
Duplicate of #725

**Comment by NillerMedDild** [comment] 2019-02-21 07:48
No fix in sight I'm afraid.

**Closed by NillerMedDild** 2019-02-21 07:48 UTC
Labels: duplicate
