### ISSUE TITLE
Mekanism Universal cables not connecting to IC2 reactor.

### ISSUE THREAD

**Issue by Keilay** [NillerMedDild/Enigmatica2Expert#1537] opened 2020-02-21 19:37 UTC
**Modpack version**
1.76a

**Issue**
Mekanism Universal cable not connecting to IC2 reactor (maximum size). They can connect to any IC2 machines i own at the moment, my CESU as well, but can;t get it to connect to the reactor, turned on or off, tried every single side. IC2 cables are connecting.

**Comment by NillerMedDild** [comment] 2020-02-21 21:19
Duplicate of #1116, I'm afraid we cannot fix this. Moving the machines to a different chunk and/or restarting the game sometimes helps.

**Closed by NillerMedDild** 2020-02-21 21:19 UTC
