### ISSUE TITLE
Extreme lag caused by pristine, as-generated AR dimension

### ISSUE THREAD

**Issue by awebneck** [NillerMedDild/Enigmatica2Expert#748] opened 2019-02-01 17:13 UTC
_Please follow the issue template, and do not delete any part of it._
_Failure to comply will result in the issue being closed._

**Issue Description**
So far I've only noticed this with the planet Stella in Proxima Centauri, but that particular dimension (114), when loaded - and after a long wait to allow it to generate - causes extreme TPS lag. the `forge tps` reveals that dimension as the only cause of lag on my server, and it goes away as soon as it is unloaded. I have built no machines there or really changed anything at all.

**Modpack version (Do not use "latest")**
1.54

**Logs**

If applicable, please upload your crash report, or latest.log to [gist](https://gist.github.com/).

**Screenshots**

**Additional context**

**Comment by NillerMedDild** [comment] 2019-02-01 17:47
Thank you for the report, I will investigate the issue.

**Comment by NillerMedDild** [comment] 2019-02-05 18:47
I'm afraid I can't reproduce this. I'll do more testing, but close it for now.

**Closed by NillerMedDild** 2019-02-05 18:47 UTC
Labels: cannot reproduce
