### ISSUE TITLE
Tinkers Casting table inventory invisible. 1.33

### ISSUE THREAD

**Issue by Menoaw** [NillerMedDild/Enigmatica2Expert#170] opened 2018-07-29 15:27 UTC
#### Issue Description
When using Tinkers Construct anything put into the casting table is invisible until it is being "cast" with the metal filling, then it will show it "cooling" then it will be invisible again once completed.

Not using any resource packs.

My friend and I are both having this issue on a private server.

#### Modpack version (Do not use "latest")
Enigmatica 2: Expert 1.33

#### Crash Report
NA

**Comment by drakkensong21** [comment] 2018-07-29 16:06
Did you read the change log

**Comment by NillerMedDild** [comment] 2018-07-29 16:57
Duplicate of #169

**Closed by NillerMedDild** 2018-07-29 16:57 UTC
