### ISSUE TITLE
Crash after Updating the pack from 1.46 to 1.49

### ISSUE THREAD

**Issue by B4rc1** [NillerMedDild/Enigmatica2Expert#544] opened 2019-01-04 17:41 UTC
## Thank you for helping us improve. #####

_Please follow the issue template, and do not delete any part of it._
_Failure to comply will result in the issue being closed._

**Issue Description**

after updating the pack from 1.46 to 1.49 the game crashes upon loading my world

**Modpack version (Do not use "latest")**
1.49

**Logs**

If applicable, please upload your crash report, or latest.log to [hastebin](https://hastebin.com/).

Crash Report: https://hastebin.com/oxigoyeges.rb
World save (in case you need it): https://drive.google.com/open?id=1RxAW_atXXKC2GS3fs-j6cynxf2WwFay9

**Screenshots**

**Additional context**

Forged aked me to remove some Tinker IO stuff. I just accepted.
Because the crash report said something about a extra utilites sound muffler, I booted up MC edit and examined the block that was mentioned in the crash log ("Block coordinates: World: (146,74,265)") but it's a AE2 smart fluix conduit (or whatever that is called. basically the big smart cable with 32 Channels).

**Comment by B4rc1** [comment] 2019-01-04 17:45
I just tested downgrading to 1.48a and there the world loads just fine.

**Comment by NillerMedDild** [comment] 2019-01-04 18:33
Believe it or not, this is a duplicate of #534 :P

**Closed by NillerMedDild** 2019-01-04 18:33 UTC

**Comment by NillerMedDild** [comment] 2019-01-04 18:34
I'm afraid I don't have a fix at the moment, please follow the other thread for updates :)
