### ISSUE TITLE
AE2 Pattern Terminal JEI Kick

### ISSUE THREAD

**Issue by Stamparas** [NillerMedDild/Enigmatica2Expert#1807] opened 2020-08-30 14:38 UTC
**Modpack version**
1.81a

**Issue**
I am going to make a recipe in ae2, going into the pattern terminal, find the recipe in JEI, then i try shift clicking it, then it kicks me for "payload may not be larger than 32767" i dont know why it doesnt work to do it anymore, i have always been able to before.
i dont know what the issue is, i would like some help with this
It works to use JEI to shift click the items into the wireless crafting terminal, just not into the pattern terminal
**Logs**
this is logs for many hours, its in the latest 30 minutes 
[latest.log](https://github.com/NillerMedDild/Enigmatica2Expert/files/5146967/latest.log)
this started happening after 16:25 ish

**Comment by NillerMedDild** [comment] 2020-08-30 19:00
This issue is most likely caused by too much data on the recipe. This could happen if the recipe accepts many different items, such as all planks. Which recipe is the issue?

In the future, please be more descriptive in your title, HELP is not a bug report :)

**Comment by Stamparas** [comment] 2020-08-30 20:34
it was the linear actuator i got this to happend with, sorry for the title, was in a rush to move my computer, so had to release it

**Comment by NillerMedDild** [comment] 2020-09-28 20:57
Hmm, works just fine for me. Has it happened repeatedly?

**Comment by Stamparas** [comment] 2020-09-28 21:03
It kept happening the same session, but not really after that, might be something together with things i got in my bag i dont know.. has not happend since then

**Comment by NillerMedDild** [comment] 2020-09-28 21:15
Cool, I'll close it for now then, thanks :)

**Closed by NillerMedDild** 2020-09-28 21:15 UTC
Labels: Status: Cannot Reproduce
