### ISSUE TITLE
Invalid Middle Backpack everytime when I open Arcane Workbench

### ISSUE THREAD

**Issue by erplsf** [NillerMedDild/Enigmatica2Expert#41] opened 2018-04-30 15:30 UTC
#### Issue Description
Invalid Middle Backpack everytime when I open Arcane Workbench
![2018-04-30-182733_1920x1080_scrot](https://user-images.githubusercontent.com/4072364/39435572-76c2e880-4ca4-11e8-977d-e9b757bed763.png)
#### What you expected to happen
Empty output slot
#### Modpack version (Do not use "latest")
1.20
#### Your most recent crash report or log file where the issue was present
https://paste.ee/p/JSmyV

**Comment by NillerMedDild** [comment] 2018-04-30 16:47
Duplicate of #35 
Please check if an issue has already been reported before posting it yourself.

**Closed by NillerMedDild** 2018-04-30 16:47 UTC
