### ISSUE TITLE
RFTools Dimensions and JourneyMap - missing dimension info

### ISSUE THREAD

**Issue by talonb** [NillerMedDild/Enigmatica2Expert#546] opened 2019-01-04 20:06 UTC
## Thank you for helping us improve. #####

_Please follow the issue template, and do not delete any part of it._
_Failure to comply will result in the issue being closed._

**Issue Description**
Console output floods and grinds the game to a halt while in an RFTools dimension

**Modpack version (Do not use "latest")**
1.49

**Logs**
If applicable, please upload your crash report, or latest.log to [hastebin](https://hastebin.com/).
I cannot upload the entire latest.log because they are between 600 and 900 MB
Here's a [small excerpt](https://github.com/NillerMedDild/Enigmatica2Expert/files/2728386/consolelog_excerpt.txt), however, I can find a way to post the whole latest.log if you need it.

**Screenshots**

**Additional context**

This is happening on a server and other users have bloated log files too.

**Comment by NillerMedDild** [comment] 2019-01-04 20:07
I moved your original issue, but thank you for the extra effort of reposting :)

**Comment by NillerMedDild** [comment] 2019-01-04 20:08
Duplicate of #545

**Closed by NillerMedDild** 2019-01-04 20:07 UTC
