### ISSUE TITLE
Weird red showing up in inventory

### ISSUE THREAD

**Issue by chajo10** [NillerMedDild/Enigmatica2Expert#1167] opened 2019-05-02 20:36 UTC
**Modpack version**
1.63

**Can the issue be reproduced?**
Yes

**Logs**
Input pastebin link to crash-report or latest log, if applicable

**Issue**
The issue I'm noticing began occurring after 1.63 came out.  Whenever you are moving your mouse about in your inventory, some of the inventory slots begin turning red.  It happens with just my inventory, as well as when I'm in my AE system.  Isn't a system breaker but semi-annoying visual glitch.

If this is a feature request, feel free to delete the template.

**Comment by NillerMedDild** [comment] 2019-05-03 06:45
Duplicate of #1166

**Closed by NillerMedDild** 2019-05-03 06:45 UTC
Labels: Type: Duplicate
