### ISSUE TITLE
Server Error Spam

### ISSUE THREAD

**Issue by mcintosh109** [NillerMedDild/Enigmatica2Expert#1174] opened 2019-05-06 23:26 UTC
**Modpack version**
Server Version 1.62

**Can the issue be reproduced?**
Yes

**Logs**
[latest Log.log](https://github.com/NillerMedDild/Enigmatica2Expert/files/3150172/latest.Log.log)

**Issue**
a user form the eu connects and then this happens

If this is a feature request, feel free to delete the template.

**Comment by Frikkle** [comment] 2019-05-07 05:46
It might not be much help in debugging, but I went through the server log and noticed a few things. They might be of use to someone looking into this after me.

- [16:49:21] Server fully started - line 11332
- [16:49:59] Hide_stampede tries connecting for the first time - line 11335
- [16:52:12] Hide_stampede joined the game - line 11345
- [16:52:13] [Astral Sorcery]: [Astral Sorcery] Waiting for server synchronization on login for Hide_stampede... - line 11364
- [16:52:14]  NetworkDispatcher exception io.netty.handler.timeout.ReadTimeoutException: null - line 11365
- [16:52:15] [net.minecraft.network.NetHandlerPlayServer]: Hide_stampede lost connection: Timed out - line 11373
- After that he "left the game", was slain by a zombie, got a grave spawned.
-[16:57:08] First error: [Netty Server IO #2/ERROR] [FML]: NetworkDispatcher exception java.io.IOException: An existing connection was forcibly closed by the remote host - line 11428.

I'm not sure to the cause of the issue, but we have seen similar connectivity issues with clients running with just (not) enough RAM. Client seems to be connecting for a long time and crashes at the last time during load or kicks user from the server after connecting. Not sure though.

Maybe any of the mod pack devs who have been around longer can add to this?

**Comment by Frikkle** [comment] 2019-05-07 05:47
Fyi: I'm running a EU-server with just EU-clients. This might also be caused by a wonky internet connection on either end. Not sure.

**Comment by NillerMedDild** [comment] 2019-05-07 06:00
Can anyone join the server?

**Comment by mcintosh109** [comment] 2019-05-07 15:46
To answer your question yes any one can join if you need to see you can hop in you just need to ask for the server ip

And to see if I have it right that message can occur if you are connecting across contents 

And in what line do I need to set the amount of ram usage in the start bat file I don’t know java very well unlike windows

On Tue, May 7, 2019, 1:00 AM Niels Pilgaard Grøndahl <notifications@github.com <mailto:notifications@github.com> > wrote:

Can anyone join the server?

**Comment by NillerMedDild** [comment] 2019-05-07 16:48
What I meant is, are other players able to connect to the server, or do they get kicked as well?

You set RAM allocation in the `settings` file.

**Comment by mcintosh109** [comment] 2019-05-07 16:49
I can and I tried locally and remotely without a vpn

**Comment by NillerMedDild** [comment] 2019-05-07 16:53
Alright. Well the crash is fairly common, it can happen because of a bad internet connection on the client side, client lag, the server not having portforwarding configured, server side firewall, client side firewall... A host of things, that are not modpack specific. I'm going to close this issue and relay you to the discord for support :)

**Closed** 2019-05-07 16:53 UTC
Labels: Type: Support
