### ISSUE TITLE
Nuclear Craft and repairing Tinkers tools

### ISSUE THREAD

**Issue by KingCookiee** [NillerMedDild/Enigmatica2Expert#1042] opened 2019-03-30 04:16 UTC
**Modpack version**
1.59a

**Can the issue be reproduced?**
Yes

**Logs**
Not Applicable 

**Issue**
A player crafted a Laser Gun from Tinkers construct with the repair part being the "Tough Alloy" from Nuclear Craft. Once the Laser Gun was completely Broken he tried to repair it with the tough alloy and it produces the broken laser gun in the output of the Forge table and consumes the 3 Tough allow needed as if its being repaired. I believe this is related to NBT issues related in this closed issue. #1016 

If this is a feature request, feel free to delete the template.

**Comment by turbodiesel4598** [comment] 2019-03-30 04:46
If this version of E2E is using v2.14c of NC (which I think it is) then the old NBT issue won’t be the cause. There’s been a problem with NC TiC parts in this pack for a little while and I’ve so far failed to understand the cause.

**Comment by NillerMedDild** [comment] 2019-04-11 07:16
Merged with #1044

**Closed by NillerMedDild** 2019-04-11 07:16 UTC
Labels: Status: Confirmation Needed, Type: Bug
