### ISSUE TITLE
Autocrafting Lag: Recreate IC2 Recipes

### ISSUE THREAD

**Issue by bluntzultimat3** [NillerMedDild/Enigmatica2Expert#363] opened 2018-11-04 17:16 UTC
**Question or Issue**

Stupid amounts of lag on server. Mostly caused by energy pipes of all kinds and AE2 throwing errors while crafting most items. Possible to update AE2 and add flux networks for power transfer that doesnt lag 

**Modpack Version**

1.41

**Additional Context**

AE2 error;

[13:45:58] [Server thread/WARN] [AE2:S]: Using CraftingManager fallback: Recipe <ic2:306> for output <1xic2.cable@0> rejected inputs [1xic2.crafting@0, 1xic2.cable@0]. NOT FOUND, please report.
[13:45:58] [Server thread/WARN] [AE2:S]: Using CraftingManager fallback: Recipe <ic2:178> for output <1xic2.crafting@1> rejected inputs [1xic2.cable@0, 1xic2.cable@0, 1xic2.cable@0, 1xitem.redstone@0, 1xitem.thermalfoundation.material@32, 1xitem.redstone@0, 1xic2.cable@0, 1xic2.cable@0, 1xic2.cable@0]. NOT FOUND, please report.

**Comment by NillerMedDild** [comment] 2018-11-04 17:57
Thank you for the report.

Are you sure AE2 is causing lag when that message is logged? It should be harmless.

The error is from AE2 Stuff, there are no updates to that.

I won't be adding Flux Networks, there are plenty of other wireless transfer methods.

**Comment by bluntzultimat3** [comment] 2018-11-04 18:00
Its spamming it something terrible aha.. and defo, i turn the ae system off and everythings fine again. Turn back on and request the craft then it dies a slow painful death haha

Ahh no worries buddy, worth a try haha

There is but they are rf/t throughput capped. Basically looking for a wireless replacement for cryostable ducts as we have about 1k in our base..

**Comment by bluntzultimat3** [comment] 2018-11-04 19:53
Quite a few items to be honest. That craft is a hv solar panel though. Its the copper cable for circuits that struggles

**Comment by NillerMedDild** [comment] 2018-11-05 16:21
Interesting, I would have thought it was a custom recipe.

**Comment by bluntzultimat3** [comment] 2018-11-06 00:00
Yehh, i defo need to transfer more rf/t lol and i would have thought the same but apparently not haha

**Comment by Atraxi** [comment] 2018-11-19 05:34
AppliedEnergistics/Applied-Energistics-2#3822

**Comment by NillerMedDild** [comment] 2018-11-19 08:38
Thanks @Atraxi :)

**Comment by NillerMedDild** [comment] 2018-11-19 08:41
It looks like I'm going to have to make every recipe that spams the console through CraftTweaker. If you know of such a recipe, please write it in this thread.

**Comment by NillerMedDild** [comment] 2018-11-19 08:41
- [ ] All Cables
- [ ] All Circuits

**Comment by SuperKael** [comment] 2018-11-20 16:13
My two cents on this issue: IC2 Experimental recipes have always been kinda weird. Back in 1.7.10, playing Infinity Evolved Expert, I noticed that when using NEI '?' button to put the ingredients into the ME crafting terminal grid for IC2 recipes, It would only put in ingredients that were themselves from IC2, vanilla ingredients wouldn't get moved. This seems like a similar-ish issue. So just throwing that out there, this looks like an IC2 problem. As for the solution, considering that this is a long-standing problem, CraftTweaker replacements are probably the best bet .-.

**Comment by lachian** [comment] 2018-11-28 07:04
I'm receiving these same console messages, but not for IC2 recipes, but for mystical agriculture recipes

version 1.44

a hastebin link of a sample showing most (all?) of the errors that come up for me : https://hastebin.com/utuxomoceg.pl

**Comment by lachian** [comment] 2018-11-29 01:10
If it matters, I believe most of the crafting patterns for these recipes were made in the Pattern Encoder vs. the Pattern Terminal.

**Comment by NillerMedDild** [comment] 2018-11-29 05:57
Does it also happen if the recipes are encoded by normal means?

**Comment by lachian** [comment] 2018-11-29 06:57
Well it's hard to tell, as it doesn't always error every time. I tried to test the theory that it was only patterns made in the Encoder. Unfortunately, when I recreate the same pattern in the Pattern Terminal I'm getting the same inconsistency with the error. Sometimes it happens, sometimes it doesn't.

**Comment by NillerMedDild** [comment] 2018-11-29 07:47
Damn :/

**Comment by bluntzultimat3** [comment] 2018-11-29 12:09
I use the AE2 encoder, don't see the point in the extra cells one at all aha...

**Comment by NillerMedDild** [comment] 2018-11-29 12:16
Do you mean the AE2 Stuff Encoder, or the Pattern Terminal?

**Comment by bluntzultimat3** [comment] 2018-11-29 12:20
The AE2 pattern term

**Comment by bluntzultimat3** [comment] 2018-11-29 12:20
Base AE2

**Comment by bookerthegeek** [comment] 2018-12-15 21:09
@NillerMedDild Would that be just the Industrial Craft 2 cables and circuits, or were some from other mods also?

**Comment by NillerMedDild** [comment] 2018-12-15 21:13
I believe some Mystical Agriculture items also have the issue.

**Comment by bookerthegeek** [comment] 2018-12-16 04:11
Gotcha. if you can post a list i'll script the out for you.

**Comment by NillerMedDild** [comment] 2018-12-16 11:47
I can't unfortunately, I plan to redo the entire mod.

**Comment by bookerthegeek** [comment] 2018-12-17 04:03
Gotcha. If you want help let me know, just ping me. :)

**Comment by NillerMedDild** [comment] 2018-12-17 05:40
Thanks, that's nice of you :D

**Comment by bluntzultimat3** [comment] 2018-12-17 15:20
Same here, If help is needed let me know :)

**Comment by NillerMedDild** [comment] 2018-12-19 07:01
@bookerthegeek I'd like some help with the IC2 recipes please, my plan of copying them over from the registry didn't pan out :P

- [ ] All IC2 Cables, with and without insulation
- [ ] All IC2 Armor
- [ ] All IC2 Tools
- [ ] Electronic & Advanced Circuit
- [ ] 
- [ ] All Mystical Agriculture Ingots
- [ ] All Mystical Agriculture Essence up/downgrade Recipes

**Comment by NillerMedDild** [comment] 2018-12-19 07:04
To check if an item has a buggy/wrong recipe, use the command `/ct recipes hand` - If the output is similar to 
`recipes.addShaped("ic2:179", <ic2:crafting:1>, [[null, null, null], [null, null, null], [null, null, null]]);`
it should be recreated.

**Comment by NillerMedDild** [comment] 2018-12-19 07:10
If possible, I would like the recipes in this form:
```<ic2:crafting:1> : [
        [
            [<ic2:cable>, <ic2:cable>, <ic2:cable>],
            [<ore:dustRedstone>, <ore:plateIron>, <ore:dustRedstone>], 
            [<ic2:cable>, <ic2:cable>, <ic2:cable>]
        ]
    ]```

**Comment by bookerthegeek** [comment] 2018-12-20 10:22
Gotcha. Starting now. :)

**Comment by bookerthegeek** [comment] 2018-12-21 03:47
Ok, I got as much as I can so far but I am going to be offline for about 14 days due to visiting Family. I uploaded to [Gist](https://gist.github.com/bookerthegeek/1a56abb521c2778d6fa6ecf76808685d) what I got done so far. It is set up for every recipe not included in the original Industrialcraft.zs file. (I pulled the shaped and shapeless recipes from the jar file.)

I've been replacing the `IC2 item naming` with the result from `/ct hand` with replace all. Hidden recipes will still be hidden. Feel free to integrate or leave till JAN 1st when I come back online. Once all the items are correctly replaced just follow the layout to put into the grid. 

Happy Holidays!

**Comment by NillerMedDild** [comment] 2018-12-21 05:35
Good work! I'll let you know how far I've gotten when you return.

Happy holidays :)

**Comment by NillerMedDild** [comment] 2018-12-21 06:54
Current progress: https://gist.github.com/NillerMedDild/e9ad1201c4797113d7da3e99e4df571c

**Comment by dh458** [comment] 2018-12-23 02:34
Thank you for your work on this. Just wanted to let you know there's a typo in the IndustrialCraft2RecreatingRecipes.zs file posted on gist above. The LV-Transformer (starting at line 124) has "ore:plankWod" instead of "ore:plankWood". Corrected version to copy-and-paste is below:

~~~~
//	LV-Transformer
	recipes.remove(<ic2:te:77>);
	recipes.addShaped(<ic2:te:77>, [
		[<ore:plankWood>, tinCableIns, <ore:plankWood>],
		[<ore:plankWood>, <ic2:crafting:5>, <ore:plankWood>],
		[<ore:plankWood>, tinCableIns, <ore:plankWood>]
	]);
~~~~

**Comment by NillerMedDild** [comment] 2018-12-23 05:39
Thanks :)

**Comment by Wenoc** [comment] 2019-01-14 17:04
In our current server, Mekanism energy tablets and mekanism energy cubes cause this.

Example for crafting a Basic Energy Cube:
`[11:56:27] [Server thread/WARN] [AE2:S]: Using CraftingManager fallback: Recipe <mekanism:energycube_0_alt_alt_alt> for output <1xtile.EnergyCube@0> rejected inputs [1xitem.AtomicAlloy@0, 1xitem.EnergyTablet@0, 1xitem.AtomicAlloy@0, 1xitem.diamond@0, 1xtile.EnergyCube@0, 1xitem.diamond@0, 1xitem.AtomicAlloy@0, 1xitem.EnergyTablet@0, 1xitem.AtomicAlloy@0]. NOT FOUND, please report.`

It looks like it has to do with items that can be charged (different metadata or NBT?). Can be reproduced in at least Enigmatica 2 expert 1.46 and 1.51. If you order an item that is complicated enough, like an Ultimate Induction Cell, it'll crash the server after a while. 

May affect any recipie that doesn't fill the pattern terminal by shift-clicking, I have not tested that.

**Comment by bookerthegeek** [comment] 2019-01-14 17:09
Mekanism might also needs it recipients done.


In other news I should be able to finish this for you by Wednesday.

**Comment by NillerMedDild** [comment] 2019-01-14 17:16
Oh boy, fixing all NBT recipes would be be a ton of work.

Sweet @bookerthegeek!

**Comment by valarnin** [comment] 2019-01-17 22:54
As a side note, the performance impact for this should be lessened if the 'Use Oredict' option is turned off on the AE2 pattern, I've noticed.

Similarly, don't ever set up autocrafting with recursive recipes (bucket > water bucket > bucket, for example), that will cause massive server lag with even small (500 bytes) autocrafts, instead just ignore the bucket outputs of the craft and storage drawer them or something, or use fluid crafter to craft things with buckets instead.

**Comment by NillerMedDild** [comment] 2019-01-22 22:19
Oh boy. This isn't actually fixing the issue.

**Comment by NillerMedDild** [comment] 2019-01-28 21:00
Oh thank god I may have been wrong. I thought I implemented the Circuit recipes but I guess not.

**Comment by NillerMedDild** [comment] 2019-01-29 10:41
I'm out of ideas, I'm not able to fix it.

**Closed by NillerMedDild** 2019-01-29 10:41 UTC
Labels: recipe, script
