### ISSUE TITLE
Cardboard Box with vanilla spawner can't be removed from ME system

### ISSUE THREAD

**Issue by Lexon78** [NillerMedDild/Enigmatica2Expert#950] opened 2019-03-07 10:58 UTC
**Modpack version**
1.57 (+1.56)

**Can the issue be reproduced?**
Yes

**Logs**

**Issue**
If use Carboard Box from Mekanism on vanilla spawner and put this box to ME system (Applied Energistics 2), then you can't take off from system. You can see this box in system, but can't by removed (propably can't be exported).

If this is a feature request, feel free to delete the template.

**Comment by NillerMedDild** [comment] 2019-03-07 11:00
Duplicate of #690

**Closed by NillerMedDild** 2019-03-07 11:00 UTC
