### ISSUE TITLE
Crash on Save and Exit

### ISSUE THREAD

**Issue by lucidfury33** [NillerMedDild/Enigmatica2Expert#959] opened 2019-03-09 00:24 UTC
**Modpack version**
1.57

**Can the issue be reproduced?**
Yes

**Logs**
https://pastebin.com/y1bmY3jk

**Issue**
When clicking save and close while in a singleplayer world, the game will crash. Every time it has happened I had LAN enabled.

**Comment by NillerMedDild** [comment] 2019-03-09 07:04
Duplicate of #419

**Closed by NillerMedDild** 2019-03-09 07:04 UTC
