### ISSUE TITLE
Advanced Generators Infinite Energy

### ISSUE THREAD

**Issue by SoybeanOil** [NillerMedDild/Enigmatica2Expert#1781] opened 2020-07-29 10:38 UTC
**Modpack version**
1.81a

**Issue**
Advanced Generators gas input receives infinite gas from "Ultimate" Gas Tank exporting into it.

**Logs**
N/A

I took a quick video of this happening in a test world to give a better idea of what I'm talking about.

https://www.youtube.com/watch?v=pXCQBesZZGU

Not shown in the video was me using something other than the gas tank such as EnderIO Gas Conduits and Mekanism Pressurized Tubes.   Both of these transfered the Etyhlene as expected and it was used up like normal.   Seems to only happen when using the Gas Tank to push the Ethylene into the Advanced Generator.

**Comment by NillerMedDild** [comment] 2020-07-29 11:48
Thanks for the report, but it is a duplicate of #1672

**Closed** 2020-08-05 19:58 UTC
Labels: Duplicate
