### ISSUE TITLE
java.lang.IllegalStateException: Recipe minecraft:crafting_table produces unregistered item minecraft:crafting_table

### ISSUE THREAD

**Issue by Mmedic23** [NillerMedDild/Enigmatica2Expert#1592] opened 2020-03-31 17:57 UTC
**Modpack version**
1.77 (and 1.78 beta)

**Issue**
On a completely fresh install of the server on a Windows 10 machine, clients receive an exception and disconnect on the "Logging in" screen.

The exception is:
`
[Client thread/FATAL]: Error executing task java.util.concurrent.ExecutionException: java.lang.IllegalStateException: Recipe minecraft:crafting_table (net.minecraft.item.crafting.ShapedRecipes@75973f7a) produces unregistered item minecraft:crafting_table (net.minecraft.item.ItemBlock@3f1fb139)
`

Clients that received exceptions were are also fresh installs on Twitch and GDLauncher, we tried with both. Both clients and the server use 64 bit Java version 1.8.0_241

**Logs**
The logs exceed pastebin size limit, I'll try attaching them directly to GitHub

[medic-client-latest.log](https://github.com/NillerMedDild/Enigmatica2Expert/files/4410688/medic-client-latest.log)

[medic-server-latest.log](https://github.com/NillerMedDild/Enigmatica2Expert/files/4410689/medic-server-latest.log)

**Comment by NillerMedDild** [comment] 2020-03-31 18:02
Thank you for the report, I will investigate the issue.

**Comment by NillerMedDild** [comment] 2020-03-31 18:06
Please try removing the mod `FastWorkbench` from both server and clients.

**Comment by Mmedic23** [comment] 2020-04-01 05:39
The exception regarding the crafting_table recipes are gone, but now "Fatally missing registry entries" error comes up on login. The client log states these entries are:

`[07:30:54] [Client thread/INFO] [FML]: Registry EntityEntry: Found a missing id from the world astralsorcery:entityılluminationspark`
`[07:30:54] [Client thread/INFO] [FML]: Registry EntityEntry: Found a missing id from the world astralsorcery:entityıtemdamageresistant`

Something I find interesting, the ID for these entries seem to contain the letter ı`ı`, which is a letter that exists in my own locale's alphabet but not in English. The capital letter `I` is converted to lowercase `ı` instead of `i` if a mod is using my PC's locale instead of the English locale.

Also please note that I've been using 1.78 to test this. I will roll back to a fresh install of the stable 1.77 with the FastWorkbench mod removed after this post.

**Comment by NillerMedDild** [comment] 2020-04-01 05:51
Which language are you using in Minecraft?

**Comment by Mmedic23** [comment] 2020-04-01 05:54
Minecraft is in English.

**Comment by NillerMedDild** [comment] 2020-04-01 05:58
And your PC language?

**Comment by Mmedic23** [comment] 2020-04-01 06:00
PC language is Turkish.

**Comment by Mmedic23** [comment] 2020-04-01 06:40
Also, I tried with 1.77 and it's behaving exactly as I described [above](https://github.com/NillerMedDild/Enigmatica2Expert/issues/1592#issuecomment-607044692).

**Comment by NillerMedDild** [comment] 2020-04-01 08:22
Would you mind changing your PC language to English, or whatever the server uses please?

**Comment by Mmedic23** [comment] 2020-04-09 00:34
Sorry for the late response, my PC was running another server so I couldn't restart it to chagne the language.

Removing Fast Workbench as you said, and changing the Windows display language to English, (then reinstalling the server) solves every problem I've had so far. I can join without any issues. Thanks for your help!

**Comment by john01dav** [comment] 2020-07-12 00:00
This issue happens on a fresh install of both the server and the client. As such, it is a bug that is in need of fixing — the fresh install combination like that should always work, without further tweating. FWIW, however, removing FastWorkbench doesn't help. Both the server and client are running Linux, and the locale command on both outputs this:
```
$ locale
LANG=en_US.UTF-8
LANGUAGE=en_US:en
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=
```

**Comment by john01dav** [comment] 2020-07-12 00:00
@NillerMedDild request re-opening of this issue

**Comment by NillerMedDild** [comment] 2020-07-12 05:31
I'll have another look :) I have still never been able to reproduce this issue though.

**Comment by NillerMedDild** [comment] 2020-07-12 18:44
I never should've closed this to be honest, I'm trying to figure out what the cause is :)

**Comment by NillerMedDild** [comment] 2020-07-12 19:10
@john01dav I discussed the issue with the developer of FastWorkbench, and he informed me that this issue is a symptom of a desync registry, reinstalling both client and server should fix this. It is a Forge error, which we can't really do anything about.

**Comment by john01dav** [comment] 2020-07-12 19:36
I just reinstalled the server and it seems to have worked. I didn't even need to reinstall the client. Thanks for your help!

**Comment by NillerMedDild** [comment] 2020-07-12 19:36
Sure thing, glad it worked.

**Closed** 2020-09-29 21:21 UTC
Labels: Invalid

**Comment by Pantheris2019** [comment] 2021-11-08 00:56
FoamFix does fix this issue for most users but not all, I have someone on my server reporting they are getting the same issue.

**Comment by Pantheris2019** [comment] 2021-11-08 00:58
Adding that the issue is actually possibly related to java as it has been discovered that a windows update with the current version of java fixes the issue.

**Comment by Pantheris2019** [comment] 2021-11-08 01:00
As in an optional update with windows fixes this issue, meaning that this traces the error way back to java itself.

**Comment by Pantheris2019** [comment] 2021-11-08 01:03
So it looks like the update KB5006738 fixes the issue with updated versions of java.  Will post an announcement on my discord as the issue has been logically, as far as I have been able to deduce, nailed down to the recent java update.

**Comment by H3LLi** [comment] 2021-12-29 21:57
HI please advice for this problem
[Client thread/FATAL]: Error executing task java.util.concurrent.ExecutionException: java.lang.IllegalStateException: Recipe minecraft:shield  produces unregistered item minecraft:shield

**Comment by Frikkle** [comment] 2021-12-31 08:33
> HI please advice for this problem [Client thread/FATAL]: Error executing task java.util.concurrent.ExecutionException: java.lang.IllegalStateException: Recipe minecraft:shield produces unregistered item minecraft:shield

Hi H3LLi, best not to reply to issues that already have been closed; especially since this is a different error than the one in the ticket. The best practice is to open a new ticket and supply us with as much information as possible (according to the issue template: game version, crash logs, other information that might be relevant). But for crashes like this, the easiest way to get support in in the #support channel of our discord servers. Have a nice year's end!

**Comment by sodaforze** [comment] 2024-02-09 18:18
I have the same problem but with the recipe from the leather leggins
