### ISSUE TITLE
Server crash when making sulfuric acid in a Chemical Reactor

### ISSUE THREAD

**Issue by arcreigh** [NillerMedDild/Enigmatica2Expert#1172] opened 2019-05-05 16:24 UTC
**Modpack version**
1.63a

**Can the issue be reproduced?**
Yes

**Logs**
https://pastebin.com/k4XjrJ8G
**Issue**
Server crash when making sulfuric acid in a Chemical Reactor

**Comment by NillerMedDild** [comment] 2019-05-05 16:25
duplicate of #1168

**Closed by NillerMedDild** 2019-05-05 16:25 UTC
Labels: Type: Duplicate

**Comment by NillerMedDild** [comment] 2019-05-05 16:27
Oh, and sorry for the inconvinience :/

**Comment by arcreigh** [comment] 2019-05-05 16:36
All good thanks Niller!
