### ISSUE TITLE
Cobalt gives ardite dust in many crushers/macerators

### ISSUE THREAD

**Issue by RedsaphirCZ** [NillerMedDild/Enigmatica2Expert#1612] opened 2020-04-05 10:07 UTC
**Modpack version**
1.78

**Issue**
Cobalt ore is processed into ardite in macerator from IC2 and other crushers.

**Comment by NillerMedDild** [comment] 2020-04-05 10:30
Duplicate of #1599

**Closed by NillerMedDild** 2020-04-05 10:30 UTC
