### ISSUE TITLE
Crash to Desktop with wireless universal crafting (AE2) in Bauble Slot

### ISSUE THREAD

**Issue by eddoww** [NillerMedDild/Enigmatica2Expert#810] opened 2019-02-10 14:49 UTC
**Issue Description**
When putting wireless universal crafting terminal in bauble slot, it will crash to desktop one tries to open inventory. 

Only way to get back into the game was by removing it manually with NBT editor (Was playing on server , lucky I own it).

**Modpack version (Do not use "latest")**

1.54

**Logs**

If applicable, please upload your crash report, or latest.log to [gist](https://gist.github.com/).

**Additional context**

In addition, without putting in bauble slot, the "crafting" option does not work (Fluid and item work)

**Comment by NillerMedDild** [comment] 2019-02-10 18:04
Duplicate of #616

**Closed by NillerMedDild** 2019-02-10 18:04 UTC
