### ISSUE TITLE
Some Mekanism Items and Blocks missing models in inventory/JEI.

### ISSUE THREAD

**Issue by Autowinto** [NillerMedDild/Enigmatica2Expert#497] opened 2018-12-31 01:20 UTC
**Issue Description**
Multiple items from the Mekanism mod lost their inventory model. These include, Atomic Disassembler, Jetpack, Gas Mask, Scuba Mask, Flamethrower, Free Runners, Armored Jetpack, Security Desk, Digital Miner, Personal Chest, Chemical Dissolution Chamber, Chemical Crystallizer, Seismic Vibrator, Solar Neutron Activator, Resistive Heater and all tiers of Energy Cubes.

Despite these models missing in JEI as well as in the player's inventory, the models are still visible when placed in-world.

**Modpack version (Do not use "latest")**

Version 1.47

**Logs**

If applicable, please upload your crash report, or latest.log to [hastebin](https://hastebin.com/).

**Screenshots**

[https://i.imgur.com/sQdVXZo.png](url)

**Additional context**

**Comment by xob** [comment] 2018-12-31 03:16
This appears to be a duplicate of issue #490

**Comment by NillerMedDild** [comment] 2018-12-31 05:07
Duplicate of #490

**Closed by NillerMedDild** 2018-12-31 05:07 UTC
Labels: duplicate
