### ISSUE TITLE
Crash with mekanism advanced solar panel in Dank null

### ISSUE THREAD

**Issue by RasiergummiBlei** [NillerMedDild/Enigmatica2Expert#1002] opened 2019-03-17 12:36 UTC
**Modpack version**
1.58

**Can the issue be reproduced?**
Yes

**Logs**
https://pastebin.com/iLRmf1TE

**Issue**
World crash on loading world if u have put a advancel solar panel by mekanism in a dank null.
works on multiplayer too.

**Comment by NillerMedDild** [comment] 2019-03-17 13:33
Duplicate of #345

**Closed by NillerMedDild** 2019-03-17 13:33 UTC
