### ISSUE TITLE
Infinite Middle Backpack from the Thaumcraft arcane Table 

### ISSUE THREAD

**Issue by Dylanonline** [NillerMedDild/Enigmatica2Expert#78] opened 2018-05-22 19:39 UTC
#### Issue Description
Infinite Middle Backpack from the Thaumcraft arcane Table, This only seems to happen with a table with no items currently in it. Once placed a few vis shards the backpack will disappear and reappear when nothing is in the table although this isn't game breaking its purely an annoyance. Thanyou 👯‍♂️ 
#### Modpack version (Do not use "latest")
1.24
#### Crash Report

[pastebin/gist/etc link here]
<img width="343" alt="capture" src="https://user-images.githubusercontent.com/39535428/40385852-46c26666-5e4b-11e8-8c40-20d7c1bb0d58.PNG">

**Comment by NillerMedDild** [comment] 2018-05-23 06:18
Duplicate of #35

**Closed by NillerMedDild** 2018-05-23 06:18 UTC
