### ISSUE TITLE
ExU2 Golden lasso

### ISSUE THREAD

**Issue by MaucnAD** [NillerMedDild/Enigmatica2Expert#460] opened 2018-12-26 00:46 UTC
**Issue Description**
Another Extra Utilities bug, very likely a bug on their end, but still reporting it here for awareness. (I will repost this in ExU github.)

Whenever I place down a mob with the golden lasso, vanilla or modded, the animal stands completely still and retains the state that it was picked up in. e.g. when I picked up a swimming mob and placed it down. it was still bobbing as if it was in the water. It eventually, at random intervals, teleports back to the block it got picked up at.

This also makes it so that if I click the lasso on a floating block, the mob floats too untill it teleports back to its place.

**Modpack version (Do not use "latest")**
Enigmatica 2 Expert 1.46
Singleplayer

**Logs**

**Screenshots**
Floating mob: https://gyazo.com/5be4c9ede2d6a497665a62bd6be451cb

Frozen mob: https://www.youtube.com/watch?v=z6B3Y8KX8Ss&

**Additional context**
- Me removing the globetrotter's sash and the mob teleporting was completely coincidental, has nothing to do with eachother.

- As you can see, you cannot interact with the mob at all. Except for when it's about to teleport away, just before it kind of 'regains his senses' and interacts with the world before teleporting.

- Flying away (approx. 50-100 blocks) from the mob seems to force it to teleport back.

- This happens with all the mobs I tried it on, pigs, cows, and modded animals.

- When you pick up a mob, travel far enough so that the spot where I picked it up is unloaded, and place it down, the mob dissapears immediately and returns to the spot that is unloaded.

- When you pick up a mob, unload the chunk, don't place it down, and return, it is not there. When you place it down afterwards, the same bug still happens.

- Wild Deer from enderzoo work interestinly different. Whenever you place them down, they (sometimes) get a reskin, and you can still interact with them (you can damage them, and pick them up again). They usually stand still, but when you bump into them, they have a running animation while they're in stand still.
Now when you pick them up more than once, doesn't matter how many times. They always end up at the spot where you first picked them up.

**Comment by Chunkey** [comment] 2018-12-26 02:53
"Random" question. Are you using vanillafix? I had this problem on an older version.

**Comment by MaucnAD** [comment] 2018-12-26 12:54
> "Random" question. Are you using vanillafix? I had this problem on an older version.

I do not use vanillafix, I have not added anything to the modpack, nor have I changed any configs.

**Comment by NillerMedDild** [comment] 2018-12-26 21:00
Just to link issues
https://github.com/rwtema/Extra-Utilities-2-Source/issues/252

**Comment by DedN00b** [comment] 2018-12-28 03:56
Alright.  I know very little about coding, modding, or mod-pack-making, so forgive me if I'm missing something useful.

Figured it out through trial and error:

Enigmatica 2 Expert v 1.46

disable randompatches-1.12.2-1.11.0.0 resolves the issue
upgrading it to randompatches-1.12.2-1.11.0.1 does not resolve the issue.
downgrading to randompatches-1.12.2-1.8.0.0 (from pack ver 1.44) also resolves the issue.

I see notes for randompatches 1.9.0.0 that a fix was implemented for something to do with moving bounding boxes, so the layman guess is there's an incompatibility between that and how ExU's lasso's move things.  I'm uncertain the etiquette for reporting these issues, and don't have more time to dig right now, so if someone else can that'd be awesome.

**Comment by TheRandomLabs** [comment] 2018-12-29 00:44
This is fixed in RandomPatches 1.12.2-1.11.0.2. :)

**Comment by NillerMedDild** [comment] 2018-12-29 08:02
Excellent, thank you for the swift fix as usual @TheRandomLabs :D

**Closed by NillerMedDild** 2018-12-29 08:02 UTC
Labels: mod issue

**Comment by DeleteMetaInf** [comment] 2022-09-10 16:11
I was having the same issue, and after some troubleshooting, I figured out that this was also caused by [Surge](https://www.curseforge.com/minecraft/mc-mods/surge). Disabling Surge solves the problem.

**Comment by DeleteMetaInf** [comment] 2022-09-10 16:12
I was having the same issue (in Enigmatica 2: Expert Skyblock), and after some troubleshooting, I figured out that this was also caused by [Surge](https://www.curseforge.com/minecraft/mc-mods/surge). Disabling Surge solves the problem. (See [this issue](https://github.com/Epoxide-Software/Surge/issues/35).)
