### ISSUE TITLE
Client crash on opening rocket inventories

### ISSUE THREAD

**Issue by superbigmax** [NillerMedDild/Enigmatica2Expert#1008] opened 2019-03-21 14:57 UTC
**Modpack version**
1.58

**Can the issue be reproduced?**
yes

**Logs**
https://pastebin.com/5xzda1R8

**Issue**
Client crash every time i open a rocket inventory, be it sat bay, chest or guidance computer. However it doens't crash just opening the main rocket gui (where you see fuel and stuff). The inventories can also be opened without any problems if they are not part of a rocket entity

If this is a feature request, feel free to delete the template.

**Comment by NillerMedDild** [comment] 2019-03-21 15:06
Duplicate of #765

**Closed by NillerMedDild** 2019-03-21 15:06 UTC
