### ISSUE TITLE
Player Rendering

### ISSUE THREAD

**Issue by RedstoneGamer123** [NillerMedDild/Enigmatica2Expert#1609] opened 2020-04-04 01:39 UTC
**Modpack version**
Input version here
1.78
**Issue**
Input short description of the issue here

When on, at least with a server, the player model won't render( armor, held item, ect) when in f5 and looking at another player unless optifine is installed.

**Logs**
Input pastebin link to crash-report or latest log, if applicable

**Comment by NillerMedDild** [comment] 2020-04-04 04:52
Thanks for the report. May I have both client and server latest.log please?

**Comment by RedstoneGamer123** [comment] 2020-04-04 14:29
The ones with me connecting to the server or the latest? As the latest happened today cus of refreshes.

**Comment by NillerMedDild** [comment] 2020-04-04 14:52
Well both ideally.

**Comment by RedstoneGamer123** [comment] 2020-04-04 16:12
[2020-04-03-2.log.gz](https://github.com/NillerMedDild/Enigmatica2Expert/files/4431900/2020-04-03-2.log.gz)
[2020-04-03-1.log.gz](https://github.com/NillerMedDild/Enigmatica2Expert/files/4431901/2020-04-03-1.log.gz)
[2020-04-03-1.log.gz](https://github.com/NillerMedDild/Enigmatica2Expert/files/4431902/2020-04-03-1.log.gz)
[2020-04-03-2.log.gz](https://github.com/NillerMedDild/Enigmatica2Expert/files/4431903/2020-04-03-2.log.gz)

**Comment by NillerMedDild** [comment] 2020-04-04 18:13
You appear to be using outdated Java. This is often caused by Twitch defaulting to an older version than you have available. Follow these steps to update.

* Make sure you have the latest 64-bit Java installed
    https://www.java.com/en/download/manual.jsp Windows Offline (64-bit) is the one you need
* Go to the Twitch Minecraft settings
* Add `-version:1.8+` to the Additional Arguments

Please let me know if that fixes it :)

**Comment by NillerMedDild** [comment] 2020-04-04 18:13
Oh I never meant to close this btw, woops.

**Comment by RedstoneGamer123** [comment] 2020-04-04 22:17
Im not running through twitch.
And my java is latest version, I always make sure to keep it updated.

**Comment by NillerMedDild** [comment] 2020-04-05 05:49
Interesting. The client logs you provided uses an ancient Java version, the same version as Twitch defaults to.

**Comment by RedstoneGamer123** [comment] 2020-04-07 12:52
If it helps I downloaded it from Twitch, but only copied the folders.

**Comment by NillerMedDild** [comment] 2020-04-07 14:15
Could you provide other latest.logs from the client please? I'm 95% sure outdated java is the cause of this issue, so I'd like some logs to prove me wrong :P

**Comment by RedstoneGamer123** [comment] 2020-04-07 16:02
[latest.log](https://github.com/NillerMedDild/Enigmatica2Expert/files/4445678/latest.log)
[2020-04-02-4.log.gz](https://github.com/NillerMedDild/Enigmatica2Expert/files/4445681/2020-04-02-4.log.gz)
[2020-04-02-5.log.gz](https://github.com/NillerMedDild/Enigmatica2Expert/files/4445682/2020-04-02-5.log.gz)
[2020-04-02-6.log.gz](https://github.com/NillerMedDild/Enigmatica2Expert/files/4445683/2020-04-02-6.log.gz)
[2020-04-03-1.log.gz](https://github.com/NillerMedDild/Enigmatica2Expert/files/4445684/2020-04-03-1.log.gz)
[2020-04-03-2.log.gz](https://github.com/NillerMedDild/Enigmatica2Expert/files/4445685/2020-04-03-2.log.gz)
[2020-04-04-1.log.gz](https://github.com/NillerMedDild/Enigmatica2Expert/files/4445686/2020-04-04-1.log.gz)
[2020-04-04-2.log.gz](https://github.com/NillerMedDild/Enigmatica2Expert/files/4445687/2020-04-04-2.log.gz)
[2020-04-04-3.log.gz](https://github.com/NillerMedDild/Enigmatica2Expert/files/4445688/2020-04-04-3.log.gz)
[2020-04-04-4.log.gz](https://github.com/NillerMedDild/Enigmatica2Expert/files/4445689/2020-04-04-4.log.gz)
[2020-04-04-5.log.gz](https://github.com/NillerMedDild/Enigmatica2Expert/files/4445690/2020-04-04-5.log.gz)
[2020-04-05-1.log.gz](https://github.com/NillerMedDild/Enigmatica2Expert/files/4445691/2020-04-05-1.log.gz)
[debug.log](https://github.com/NillerMedDild/Enigmatica2Expert/files/4445693/debug.log)
[debug-1.log.gz](https://github.com/NillerMedDild/Enigmatica2Expert/files/4445694/debug-1.log.gz)
[debug-2.log.gz](https://github.com/NillerMedDild/Enigmatica2Expert/files/4445695/debug-2.log.gz)
[debug-3.log.gz](https://github.com/NillerMedDild/Enigmatica2Expert/files/4445696/debug-3.log.gz)
[debug-4.log.gz](https://github.com/NillerMedDild/Enigmatica2Expert/files/4445698/debug-4.log.gz)
[debug-5.log.gz](https://github.com/NillerMedDild/Enigmatica2Expert/files/4445699/debug-5.log.gz)

**Comment by RedstoneGamer123** [comment] 2020-04-07 16:02
There's a bunch

**Comment by NillerMedDild** [comment] 2020-04-07 16:21
Thanks! They say the same thing, make sure Minecraft uses your newest Java and the problem should go away :)

**Closed by NillerMedDild** 2020-04-07 16:21 UTC
Labels: Java Version

**Comment by RedstoneGamer123** [comment] 2020-04-07 16:23
How would I do that?
Ive just never had this problem till this pack :/

**Comment by RedstoneGamer123** [comment] 2020-04-07 16:23
How would I do that?
Ive just never had this problem till this pack :/

**Comment by NillerMedDild** [comment] 2020-04-07 17:11
That depends, what are you using to launch Minecraft?

**Comment by RedstoneGamer123** [comment] 2020-04-07 20:52
The minecraft launcher

**Comment by NillerMedDild** [comment] 2020-04-07 21:17
Oh boy, it's complicated ><
* Click Installations
* Click the Forge version you're using
* Click more options
* Input Java Executable through the Browse button

**Comment by RedstoneGamer123** [comment] 2020-04-08 02:54
What java executable? java.exe, javaws.exe, javacpl.exe, javaw.exe?

**Comment by RedstoneGamer123** [comment] 2020-04-08 02:54
Or something else?

**Comment by NillerMedDild** [comment] 2020-04-08 05:39
Jave.exe - If that doesn't work add `-version:1.8+` to the arguments below the java executable line.

**Comment by RedstoneGamer123** [comment] 2020-04-09 23:40
Cool, -version:1.8+ Works! :) Thx!
