### ISSUE TITLE
Possible solution for recipe problem in Mekanism (Ultimate Fluid Tank)

### ISSUE THREAD

**Issue by KingFishQiu** [NillerMedDild/Enigmatica2Expert#366] opened 2018-11-05 19:16 UTC
## Thank you for helping us improve. #####

_Please follow the issue template, and do not delete any part of it._
_Failure to comply will result in the issue being closed._

**Issue Description**
It might be the problem stated in https://github.com/NillerMedDild/Enigmatica2Expert/issues/333 , in short, recipes with **ultimate fluid tank** don't work.

Just want to provide a possible quick solution before the problem is officially fixed. Downgrade the crafttweaker to 1.9. I don't know if it will influence other recipes but the problem is solved. 

**Modpack version (Do not use "latest")**
1.41

**Logs**

If applicable, please upload your crash report, or latest.log to [hastebin](https://hastebin.com/).

**Screenshots**

**Additional context**

**Comment by NillerMedDild** [comment] 2018-11-05 20:29
Thanks for the report, it is indeed a duplicate of #333

**Closed by NillerMedDild** 2018-11-05 20:29 UTC
