### ISSUE TITLE
Cyclic Auto Crafter Dupe

### ISSUE THREAD

**Issue by ghost** [NillerMedDild/Enigmatica2Expert#1506] opened 2020-01-31 19:47 UTC
**Modpack version**
1.76a

**Issue**
The cyclic auto crafter dupes all single item recipes if supplied with power after you take the original item out.

**Comment by NillerMedDild** [comment] 2020-01-31 19:50
Thanks for the report, why did you close it? :)

**Comment by MrSirDude** [comment] 2020-01-31 19:51
I accidentally submitted it early, I was going to make it more detailed.

**Comment by urikkiru** [comment] 2020-02-08 17:18
This happened just now for me as well. It's hard to describe how to reproduce, but I had two 3x3 Cyclic autocrafters chained together with just a simple hopper.(The hopper feeding items from the output of one crafter into another) Hit this problem when I would try to empty out the crafter so I could change recipes. This dupe bug seems to persist until you put some other recipe into the crafter.

**Comment by vbandaruk** [comment] 2020-04-02 21:18
v1.76a allowed duping of not just ores but some recipes like conduit binder (Ender IO) and even mekanism casings. 

v1.77 I am able to produce only those that the compacting drawer recognizes i.e. the following two types:
blocks -> ingots -> nuggets
log wood -> wood planks

How the dupe works: 
Place a block of iron in the crafting grid that stores recipes. 
On removing the block manually, the auto crafter starts producing ingots.  
This keeps happening until a block (say gold) is placed in the crafting grid.  If this block can be made into ingots then the crafter starts producing them.

If the duping doesn't start automatically on block removal, try setting the recipe using JEI ('+' button to shift recipes in)

Have not played 1.78 yet.

**Closed** 2021-08-11 20:51 UTC
Labels: Mod Issue, Status: Fixed In Next Release
