### ISSUE TITLE
Game crash when crafing advanced solar generator from mekanism

### ISSUE THREAD

**Issue by TeamZXXX** [NillerMedDild/Enigmatica2Expert#946] opened 2019-03-06 11:29 UTC
**Modpack version**
1.56

**Can the issue be reproduced?**
Yes
**Logs**
none
**Issue**
The game would crash if you tried to craft the advanced solar generator with and without shift clicking items into the crafting grid. Seems to be either the large iron plate or the small solars that are causing this.

**Comment by NillerMedDild** [comment] 2019-03-06 13:09
Duplicate of #345

**Closed by NillerMedDild** 2019-03-06 13:09 UTC
