### ISSUE TITLE
Immersive Engineering Crusher Output Problem

### ISSUE THREAD

**Issue by TheMegaOverlord** [NillerMedDild/Enigmatica2Expert#1859] opened 2020-11-29 07:06 UTC
[2020-11-29-1.log](https://github.com/NillerMedDild/Enigmatica2Expert/files/5611778/2020-11-29-1.log)

**Modpack version**
1.82a

**Issue**
When putting certain items into the crusher from Immersive Engineering, ores such as nether ores or raw products such as coal will not output anything when being crushed. Rather, the item dispensed into the crusher will leave the machine stuck in an endless loop. This will also prevent the machine from outputting other products if you dispense anything else into the crusher. 

**Logs**
Log attached.

**Comment by NillerMedDild** [comment] 2020-11-29 07:41
Duplicate of #1841, see [this comment](https://github.com/NillerMedDild/Enigmatica2Expert/issues/1841#issuecomment-734882400) for a temporary fix :)

**Closed by NillerMedDild** 2020-11-29 07:41 UTC
