### ISSUE TITLE
Fluid Duplication

### ISSUE THREAD

**Issue by arcain782** [NillerMedDild/Enigmatica2Expert#1196] opened 2019-05-19 12:11 UTC
**Modpack version**
1.63a

**Can the issue be reproduced?**
Yes

**Logs**
N/A

**Issue Reproduction**
1. Setup at least (2) **Fluid Storage Tanks** [ **(#12163)**_Cyclic_ ] side by side. 
2. Connect **Fluid Conduit** [**(#8267/0)** _EnderIO_] to bottom of each
3. Configure the conduits to extract from the tanks and insert into a third **Fluid Storage Tank**.
4. Fill a **Portable Tank** [(Basic) **(#5014/0)**_Thermal Expansion_] with any amount of any liquid (tested with Liquid XP and Pink slime)
5. Use the **Portable Tank** to insert liquid into either of the first 2 fluid storage tanks and then draw from the third tank as it is still being piped from the first 2 tanks into the third. Rinse and repeat and you'll notice you end up with way more liquid than you started with.

**Screenshot**
https://i.imgur.com/4AvgexN.jpg

I did not test this enough to find exactly where the dupe is taking place hence me outlining everything I did when the issue happened. I suspect it is with the portable tank since the other fluid dupe issue currently reported (#1180 ) also involved them.

**Comment by NillerMedDild** [comment] 2019-05-19 17:24
Duplicate of #1180, should be fixed in the newest version :)

**Comment by NillerMedDild** [comment] 2019-05-19 17:24
But thank you very much for the detailed report, I appreciate it.

**Closed by NillerMedDild** 2019-05-19 17:24 UTC
