### ISSUE TITLE
hippogryphs near the player cause the player's client to crash

### ISSUE THREAD

**Issue by coledot** [NillerMedDild/Enigmatica2Expert#83] opened 2018-05-30 00:40 UTC
#### Issue Description

There appears to be some state the hippogryphs are getting into that are causing nearby player's clients to crash. Unfortunately, I don't have any idea what the cause is. The error is:

```
Description: Ticking entity

java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.Boolean
	at com.github.alexthe666.iceandfire.entity.EntityHippogryph.isHovering(EntityHippogryph.java:459)
```

It appears to be the same problem as described in https://github.com/Alex-the-666/Ice_and_Fire/issues/461; however, the mod author had indicated Primitive Mobs as the source of the crash. Primitive Mobs is not present in this modpack.

The error has happened to myself and at least two other players on the server I play on.

#### Modpack version (Do not use "latest")

Enigmatica 2: Expert 1.25

#### Crash Report

Full crash log can be found here: https://pastebin.com/QvG90UeY

**Comment by Lukas45** [comment] 2018-05-30 07:44
Sadly known issue.
It's a conflict issue between Thaumcraft and I&F.
Nothing can be done, other than deleting those mobs with commands or command blocks.
We're waiting for Thaumcraft to update (with a server-stable build), to see if the issue is still present. If it is, we're likely to temporarily remove I&F.

For now, our solution is 4 repeating command blocks running /cofh killall [mobs]

**Comment by Alex-the-666** [comment] 2018-07-05 00:02
@NillerMedDild this issue has been resolved in Thaumcraft BETA 17

**Comment by NillerMedDild** [comment] 2018-07-05 06:53
Ah yes, I did update, just forgot to close this. Thank you :)

**Closed by NillerMedDild** 2018-07-05 06:53 UTC
Labels: mod issue
