### ISSUE TITLE
ultimate tier installer

### ISSUE THREAD

**Issue by niklas2233** [NillerMedDild/Enigmatica2Expert#1112] opened 2019-04-16 20:52 UTC
**Modpack version**
1.60
**Can the issue be reproduced?**
Yes

**Issue**
make the recipe harder if its not wrong on in my client

http://prntscr.com/ncwgye

**Comment by NillerMedDild** [comment] 2019-04-16 20:53
duplicate of #822

**Closed by NillerMedDild** 2019-04-16 20:53 UTC
