### ISSUE TITLE
Mekanism, Chemical Oxidizer and Thermal Evaporation Controller

### ISSUE THREAD

**Issue by Dragon763** [NillerMedDild/Enigmatica2Expert#361] opened 2018-11-02 13:10 UTC
## Thank you for helping us improve. #####

_Please follow the issue template, and do not delete any part of it._
_Failure to comply will result in the issue being closed._

**Issue Description**
I can't craft  Chemical Oxidizer and Thermal Evaporation Controller.

**Modpack version (Do not use "latest")**
1.41

**Logs**

If applicable, please upload your crash report, or latest.log to [hastebin](https://hastebin.com/).

**Screenshots**

https://imgur.com/a/3zRWIGu

**Additional context**

**Comment by Dragon763** [comment] 2018-11-02 17:55
Is this tank not Ultimate Fluid Tank?

**Comment by NillerMedDild** [comment] 2018-11-02 18:32
Duplicate of #333

**Comment by NillerMedDild** [comment] 2018-11-02 18:32
Anthony is incorrect, the recipe is bugged.

**Closed by NillerMedDild** 2018-11-02 18:32 UTC
