### ISSUE TITLE
Dupe Bug.

### ISSUE THREAD

**Issue by GoldenKeyboard** [NillerMedDild/Enigmatica2Expert#435] opened 2018-12-15 02:58 UTC
You can dupe lapis lazuli using an ic2 compressor; I assume this is not intentional.
https://i.gyazo.com/f5997268b0463c6ca27657aec2f098c1.png

**Comment by drakkensong21** [comment] 2018-12-15 03:10
Dupe of #186

**Comment by drakkensong21** [comment] 2018-12-15 03:10
Dupe of #421

**Comment by NillerMedDild** [comment] 2018-12-15 15:59
Duplicate of #390

**Closed by NillerMedDild** 2018-12-15 15:59 UTC
