### ISSUE TITLE
Removing Space station ID chip. 

### ISSUE THREAD

**Issue by Rumple1028** [NillerMedDild/Enigmatica2Expert#982] opened 2019-03-11 21:38 UTC
**Modpack version**
1.58

**Can the issue be reproduced?**
Yes

**Logs**
The game crashed whilst ticking player
The game crashed whilst ticking player
Error: java.lang.IllegalStateException: Called getProgress on neither server or client - what are you?

**Issue**
I can't removed the space station ID chip from the guidance computer in my rocket while on the space station and replace it with the planet ID chip.  Game crashes every time.

If this is a feature request, feel free to delete the template.

**Comment by MaxNeedsSnacks** [comment] 2019-03-11 21:44
Can you post your full latest.log to pastebin and paste the link here? Just the stacktrace won't be enough for me to report the issue to the AR tracker, unfortunately

**Comment by NillerMedDild** [comment] 2019-03-12 05:52
Duplicate of #765 - thought that was fixed though.

**Comment by MaxNeedsSnacks** [comment] 2019-03-12 11:07
Fixed in aidancbrady/Mekanism@047c830.

This shouldn't occur anymore once we either switch back to the regular Mekanism or once Dizzy's fork gets the update as well.

**Closed by MaxNeedsSnacks** 2019-03-12 11:07 UTC
Labels: mod issue, more-information-needed
