### ISSUE TITLE
Crash with Compact Machines

### ISSUE THREAD

**Issue by Old-Man-D** [NillerMedDild/Enigmatica2Expert#1141] opened 2019-04-24 08:37 UTC
**Modpack version**
1.61

**Can the issue be reproduced?**
Yes

**Logs**
https://pastebin.com/K8xvj5wf

**Issue**
If you try and use the preview button to enter a compact machine while the tool is in your inventory, but not in your hand, it crashes.  Entering the machine directly with the tool is fine.

**Comment by NillerMedDild** [comment] 2019-04-24 09:01
Does this happen with version 1.62?

**Comment by Frikkle** [comment] 2019-04-24 15:24
Just tested this on 1.62 in both SP and MP; cannot reproduce. Tried this with the Personal Shrinking Device in all types of slots (inventory, hotbar, off-hand, etc.).

An issue I did come across is that if you try to change the Machine's name; and click the checkmark box, the server does kick you with a "Connection Lost. - A fatal error has occured, this connection is terminated" error.

Server side logs [here](https://pastebin.com/qCa5tgXS).

So if @Old-Man-D indeed means the preview button; I cannot reproduce. If he means the name changing thing I can confirm. So we should then either adjust this issue to reflect the name-change thing or create a new one for it.

**Comment by Old-Man-D** [comment] 2019-04-24 15:44
I’m not using any tunnels on these compact machines yet. I will update tonight to 1.62 and let you know my results. But specifically, I am talking about the little button that appears in the lower right corner of the preview window, when the shrinking device is present in your inventory.

**Comment by Frikkle** [comment] 2019-04-24 15:48
> I am talking about the little button that appears in the lower right corner of the preview window, when the shrinking device is present in your inventory.

Yeah; that is the preview button indeed. I cannot reproduce that on 1.62. I'm installing 1.61 now to check this in singleplayer. Could you confirm that the preview also causes a crash for you when the shrinking device is in your inventory but not in your hand?

**Comment by Old-Man-D** [comment] 2019-04-24 15:54
Also, I’m using a server FYI, in case that makes a difference

**Comment by Frikkle** [comment] 2019-04-24 15:56
It does make a difference; I just wondered if it also crashes in single player for you. That might help in pinpointing the behavior. I don't have a 1.61 server running anymore so I can't easily debug this on 1.61 MP.

**Comment by Frikkle** [comment] 2019-04-24 15:57
Update: I can't reproduce it on 1.61 stock in SP.

**Comment by NillerMedDild** [comment] 2019-04-24 15:57
The preview crash was fixed by 1.62

**Closed by NillerMedDild** 2019-04-24 15:57 UTC
Labels: Status: Available, Type: Mod Issue
