### ISSUE TITLE
Game crashes before titlescreen.

### ISSUE THREAD

**Issue by Exo594** [NillerMedDild/Enigmatica2Expert#1049] opened 2019-03-30 15:21 UTC
**Modpack version**
1.59a

**Can the issue be reproduced?**
Unknown. Happens regularly for me.

Java updated to 201 after seeing another report.

I have reinstalled 1.59a several times, they have all crashed.
Downgraded to 1.51, issue persists.

**Logs**
https://pastebin.com/qyCSUL5x (1.59a log)
https://pastebin.com/Xavg1urG (1.51 log)

**Issue**
Game crashes between Minecraft launcher and game title-screen.

**Comment by MaxNeedsSnacks** [comment] 2019-03-30 15:34
Duplicate of #1020

**Comment by MaxNeedsSnacks** [comment] 2019-03-30 15:35
Please try the save in #1020 first and then get back to me on whether it worked

**Comment by Kuktar** [comment] 2019-03-30 15:35
Seems that both those logs are using the outdated java.

Follow this


https://www.reddit.com/r/feedthebeast/comments/80nhie/twitch_launcher_forcing_old_java_versions_on_you/




Christopher Kuhn,
Semper Fidelis

**Closed** 2019-03-30 15:35 UTC
Labels: Type: Duplicate

**Comment by MaxNeedsSnacks** [comment] 2019-03-30 15:36
Possible causes for InvocationTargetExceptions that I know of:

- Outdated Java
- Corrupt Installation
- Optifine fucking things up
- Library files sticking around when they shouldn't
- Some ASM fucking things up

**Comment by Exo594** [comment] 2019-03-31 01:38
Creating a new install and moving the save-files over has fixed the issue. I'm glad it was something that simple.
